src/base/objects/BT_Product__c/BT_Product__c.object-meta.xml
<CustomObject>
    <label>BT Product</label>
    <nameField>
        <label>BT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/BT_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the account this opportunity&apos;s node is associated with.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BT Products</relationshipLabel>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Availability_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Availability_Commitment__c</fullName>
    <label>Availability Commitment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>99.9%</fullName>
            </value>
            <value>
                <fullName>99.0%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>No Billing (Delegation)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Has_Standard_Product__c.field-meta.xml
<CustomField>
    <fullName>Has_Standard_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Standard Product</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Node__c.field-meta.xml
<CustomField>
    <fullName>Node__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The node associated with this opportunity</description>
    <label>Node</label>
    <referenceTo>Node__c</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Node_Price__c.field-meta.xml
<CustomField>
    <fullName>Node_Price__c</fullName>
    <description>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. Price/node/month. This will auto-populate to give an estimate based off our pricing sheet.</description>
    <inlineHelpText>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. Price/node/month. This will auto-populate to give an estimate based off our pricing sheet.</inlineHelpText>
    <label>Node Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity associated with this node.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/base/objects/BT_Product__c/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <description>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. This value refers to either Participatory Fees OR Revenue Share to Coinbase for Coinbase Pay opportunities. This will auto-populate to give an estimate based off our pricing sheet.</description>
    <inlineHelpText>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. This value refers to either Participatory Fees OR Revenue Share to Coinbase for Coinbase Pay opportunities. This will auto-populate to give an estimate based off our pricing sheet.</inlineHelpText>
    <label>Participatory Fee/Rev Share</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The number of nodes</description>
    <label>Node Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the sub total that is matched with sub total formula so it can be used in the opportunity rollup.</description>
    <inlineHelpText>This is will automatically populate based on the number of tokens staked and/or quantity of nodes.</inlineHelpText>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Tokens_Staked__c.field-meta.xml
<CustomField>
    <fullName>Tokens_Staked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of tokens staked for this protocol</description>
    <inlineHelpText>This value refers to either Tokens Staked OR Annual Transacting Users for Coinbase Pay opportunities.</inlineHelpText>
    <label>Tokens Staked/Annual Users</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Node__c/Node__c.object-meta.xml
<CustomObject>
    <description>This is the given node offering of a given protocol.</description>
    <label>Node</label>
    <nameField>
        <label>Node</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/objects/Node__c/fields/Base_Node_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Node_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the standard price we charge for this node.</description>
    <label>Base Node Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Node__c/fields/Delegation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Delegation_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The percentage of rewards the user is paying Bison Trails to delegate to a BT node.</description>
    <label>Delegation Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/Node__c/fields/Node_Family__c.field-meta.xml
<CustomField>
    <fullName>Node_Family__c</fullName>
    <description>This is the type of node in the format {Protocol-Node Type}</description>
    <inlineHelpText>{Protocol-Node Type}</inlineHelpText>
    <label>Node Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Node__c/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the participation fee. Only required for Participation nodes.</description>
    <inlineHelpText>Not required for QT. Leave blank.</inlineHelpText>
    <label>Participatory Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/Node__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Protocol one which this type of node is run.</description>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Node_Count__c.field-meta.xml
<CustomField>
    <fullName>Node_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of nodes on opportunity.</description>
    <label>Node Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Opportunity/recordTypes/Cloud_Pipeline.recordType-meta.xml
<RecordType>
    <fullName>Cloud_Pipeline</fullName>
    <active>true</active>
    <businessProcess>Participation Sales Process</businessProcess>
    <label>Cloud Pipeline</label>
</RecordType>

src/base/objects/OpportunityLineItem/fields/Availability_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Availability_Commitment__c</fullName>
    <label>Availability Commitment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>99.9%</fullName>
            </value>
            <value>
                <fullName>99.0%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>No Billing (Delegation)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/OpportunityLineItem/fields/BT_Product__c.field-meta.xml
<CustomField>
    <fullName>BT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BT Product</label>
    <referenceTo>BT_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Had_BT_Product__c.field-meta.xml
<CustomField>
    <fullName>Had_BT_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Had BT Product</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Hosted_Service__c.field-meta.xml
<CustomField>
    <fullName>Hosted_Service__c</fullName>
    <label>Hosted Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Node_Count__c.field-meta.xml
<CustomField>
    <fullName>Node_Count__c</fullName>
    <label>Node Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Participatory Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <label>Protocol</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fee__c</fullName>
    <label>Subscription Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/PricebookEntry/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <description>The participatory fee % (optional).</description>
    <inlineHelpText>Only required for participation price book.</inlineHelpText>
    <label>Participatory Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/Product2/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The protocol associated with this product.</description>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/objects/Protocol__c/fields/Inflation_Rate__c.field-meta.xml
<CustomField>
    <fullName>Inflation_Rate__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The current inflation rate of the protocol.</description>
    <inlineHelpText>This rate should be updated regularly to ensure accurate forecasting.</inlineHelpText>
    <label>Inflation Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/Protocol__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The price of the token in USD. Updated every week.</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Protocol__c/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <description>The token&apos;s ticker symbol.</description>
    <label>Symbol</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/base/classes/TA_BTProduct_CheckStandardProductTest.cls
@isTest
public class TA_BTProduct_CheckStandardProductTest {
  @testSetup
  static void setup() {
    Pricebook2 standardPricebook = new Pricebook2(
      Id = Test.getStandardPricebookId(),
      IsActive = true
    );
    update standardPricebook;

    Product2 product = new Product2(Name = 'Standard Sale', IsActive = true);
    insert product;

    PricebookEntry pbe = new PricebookEntry(
      Pricebook2Id = standardPricebook.Id,
      Product2Id = product.Id,
      isActive = true,
      UnitPrice = 1.00
    );
    insert pbe;

    List<Account> a = TestDataHelper.getAccounts(1, true);
    List<Opportunity> opp = TestDataHelper.getOpportunities(a[0].Id, 1, false);
    opp[0]
      .RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
      .get('Cloud_Pipeline')
      .getRecordTypeId();
    opp[0].closeDate = System.today().addDays(30);
    insert opp;

    Protocol__c protocol = new Protocol__c();
    protocol.Inflation_Rate__c = 1.00;
    protocol.Price__c = 0.15;
    protocol.Name = 'My Test Token';
    protocol.Symbol__c = 'MTT';

    insert protocol;

    Node__c node = new Node__c();
    node.Base_Node_Price__c = 1.00;
    node.Delegation_Fee__c = 5.00;
    node.Name = 'Test Node';
    node.Node_Family__c = 'Participation';
    node.Participatory_Fee__c = 5.00;
    node.Protocol__c = protocol.Id;
    insert node;

    BT_Product__c btp = new BT_Product__c();
    btp.Account__c = a[0].Id;
    btp.Opportunity__c = opp[0].Id;
    btp.Availability_Commitment__c = '99.0%';
    btp.Billing_Frequency__c = 'Monthly';
    btp.Quantity__c = 1.0;
    btp.Participatory_Fee__c = 10.00;
    btp.Node_Price__c = 100.00;
    btp.Node__c = node.Id;
    btp.Tokens_Staked__c = 5;
    insert btp;
  }

  @isTest
  static void createBTProductHasStdProduct() {
    Pricebook2 standardPricebook = [SELECT Id FROM Pricebook2 LIMIT 1];
    Account a = [SELECT Id FROM Account LIMIT 1];
    Node__c node = [
      SELECT Id, Node_Family__c, Protocol__r.Name
      FROM Node__c
      LIMIT 1
    ];
    Protocol__c protocol = [SELECT Id FROM Protocol__c LIMIT 1];
    Opportunity opp = [SELECT Id, PriceBook2Id FROM Opportunity LIMIT 1];
    BT_Product__c btp = [
      SELECT
        Id,
        Account__c,
        Opportunity__c,
        Availability_Commitment__c,
        Billing_Frequency__c,
        Quantity__c,
        Participatory_Fee__c,
        Node_Price__c,
        Node__c,
        Has_Standard_Product__c
      FROM BT_Product__c
      LIMIT 1
    ];

    System.assertEquals(
      true,
      btp.Has_Standard_Product__c,
      'Has standard product field should be updated to true after record insert!'
    );
    System.assertEquals(
      Test.getStandardPricebookId(),
      opp.PriceBook2Id,
      'Standard price book id should be updated on opportunity!'
    );
    System.assertEquals(
      1,
      [SELECT Id FROM OpportunityLineItem WHERE BT_Product__c = :btp.Id].size(),
      'An opportunity product record should get created to the BT product record!'
    );
    System.assertEquals(
      btp.Billing_Frequency__c,
      [
        SELECT Id, Billing_Frequency__c
        FROM OpportunityLineItem
        WHERE BT_Product__c = :btp.Id
      ]
      .Billing_Frequency__c,
      'An opportunity product record should should have the same billing frequency as the BT product record!'
    );

    btp.Billing_Frequency__c = 'Yearly';
    btp.Availability_Commitment__c = '99.0%';
    update btp;

    BT_Product__c updatedRecord = [
      SELECT
        Id,
        Availability_Commitment__c,
        Billing_Frequency__c,
        Node__r.Node_Family__c,
        Quantity__c,
        Participatory_Fee__c,
        Opportunity__r.CloseDate,
        Node_Price__c,
        Sub_Total__c,
        (
          SELECT
            Availability_Commitment__c,
            BT_Product__c,
            Billing_Frequency__c,
            Had_BT_Product__c,
            Hosted_Service__c,
            Node_Count__c,
            Participatory_Fee__c,
            Quantity,
            ServiceDate,
            Subscription_Fee__c,
            UnitPrice
          FROM Opportunity_Product__r
        )
      FROM BT_Product__c
      WHERE Id = :btp.Id
    ];

    System.assertEquals(
      'Yearly',
      updatedRecord.Opportunity_Product__r[0].Billing_Frequency__c,
      'Billing frequesncy should be updated!'
    );
    System.assertEquals(
      '99.0%',
      updatedRecord.Opportunity_Product__r[0].Availability_Commitment__c,
      'Availability commitment should be updated!'
    );
  }

  @isTest
  static void createBTProductHasNoStdProduct() {
    Pricebook2 standardPricebook = [SELECT Id FROM Pricebook2 LIMIT 1];
    Account a = [SELECT Id FROM Account LIMIT 1];
    Node__c node = [
      SELECT Id, Node_Family__c, Protocol__r.Name
      FROM Node__c
      LIMIT 1
    ];
    Protocol__c protocol = [SELECT Id FROM Protocol__c LIMIT 1];
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    BT_Product__c btp = [
      SELECT
        Id,
        Account__c,
        Opportunity__c,
        Availability_Commitment__c,
        Billing_Frequency__c,
        Quantity__c,
        Participatory_Fee__c,
        Node_Price__c,
        Node__c,
        Sub_Total__c
      FROM BT_Product__c
      LIMIT 1
    ];

    List<OpportunityLineItem> oli = [
      SELECT
        Id,
        OpportunityId,
        Availability_Commitment__c,
        Billing_Frequency__c,
        Had_BT_Product__c,
        Hosted_Service__c,
        Node_Count__c,
        Participatory_Fee__c,
        Protocol__c,
        Quantity,
        Subscription_Fee__c,
        UnitPrice
      FROM OpportunityLineItem
    ];

    System.assertEquals(
      1,
      oli.size(),
      'New Opportunity Product record should get created for the BT product!'
    );
    System.assertEquals(opp.Id, oli[0].OpportunityId);
    System.assertEquals(
      btp.Availability_Commitment__c,
      oli[0].Availability_Commitment__c
    );
    System.assertEquals(btp.Billing_Frequency__c, oli[0].Billing_Frequency__c);
    System.assertEquals(true, oli[0].Had_BT_Product__c);
    System.assertEquals('Network Participation', oli[0].Hosted_Service__c);
    System.assertEquals(btp.Quantity__c, oli[0].Node_Count__c);
    System.assertEquals(btp.Participatory_Fee__c, oli[0].Participatory_Fee__c);
    System.assertEquals(Node.Protocol__r.Name, oli[0].Protocol__c);
    System.assertEquals(1, oli[0].Quantity);
    System.assertEquals(btp.Node_Price__c, oli[0].Subscription_Fee__c);
    System.assertEquals(btp.Sub_Total__c, oli[0].UnitPrice);
  }
}