src/base/objects/BT_Product__c/BT_Product__c.object-meta.xml
<CustomObject>
    <label>BT Product</label>
    <nameField>
        <label>BT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/BT_Product__c/fields/Availability_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Availability_Commitment__c</fullName>
    <label>Availability Commitment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>99.9%</fullName>
            </value>
            <value>
                <fullName>99.0%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>No Billing (Delegation)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Has_Standard_Product__c.field-meta.xml
<CustomField>
    <fullName>Has_Standard_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Standard Product</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Node__c.field-meta.xml
<CustomField>
    <fullName>Node__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The node associated with this opportunity</description>
    <label>Node</label>
    <referenceTo>Node__c</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Node_Price__c.field-meta.xml
<CustomField>
    <fullName>Node_Price__c</fullName>
    <description>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. Price/node/month. This will auto-populate to give an estimate based off our pricing sheet.</description>
    <inlineHelpText>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. Price/node/month. This will auto-populate to give an estimate based off our pricing sheet.</inlineHelpText>
    <label>Node Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity associated with this node.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/base/objects/BT_Product__c/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <description>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. This value refers to either Participatory Fees OR Revenue Share to Coinbase for Coinbase Pay opportunities. This will auto-populate to give an estimate based off our pricing sheet.</description>
    <inlineHelpText>LEAVE BLANK UNTIL YOU HAVE THE AGREED UPON VALUE. This value refers to either Participatory Fees OR Revenue Share to Coinbase for Coinbase Pay opportunities. This will auto-populate to give an estimate based off our pricing sheet.</inlineHelpText>
    <label>Participatory Fee/Rev Share</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The number of nodes</description>
    <label>Node Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the sub total that is matched with sub total formula so it can be used in the opportunity rollup.</description>
    <inlineHelpText>This is will automatically populate based on the number of tokens staked and/or quantity of nodes.</inlineHelpText>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Node__c/Node__c.object-meta.xml
<CustomObject>
    <description>This is the given node offering of a given protocol.</description>
    <label>Node</label>
    <nameField>
        <label>Node</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/objects/Node__c/fields/Node_Family__c.field-meta.xml
<CustomField>
    <fullName>Node_Family__c</fullName>
    <description>This is the type of node in the format {Protocol-Node Type}</description>
    <inlineHelpText>{Protocol-Node Type}</inlineHelpText>
    <label>Node Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Node__c/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the participation fee. Only required for Participation nodes.</description>
    <inlineHelpText>Not required for QT. Leave blank.</inlineHelpText>
    <label>Participatory Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/Node__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Protocol one which this type of node is run.</description>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Node_Count__c.field-meta.xml
<CustomField>
    <fullName>Node_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of nodes on opportunity.</description>
    <label>Node Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Availability_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Availability_Commitment__c</fullName>
    <label>Availability Commitment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>99.9%</fullName>
            </value>
            <value>
                <fullName>99.0%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>No Billing (Delegation)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/OpportunityLineItem/fields/BT_Product__c.field-meta.xml
<CustomField>
    <fullName>BT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BT Product</label>
    <referenceTo>BT_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Had_BT_Product__c.field-meta.xml
<CustomField>
    <fullName>Had_BT_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Had BT Product</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Hosted_Service__c.field-meta.xml
<CustomField>
    <fullName>Hosted_Service__c</fullName>
    <label>Hosted Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Node_Count__c.field-meta.xml
<CustomField>
    <fullName>Node_Count__c</fullName>
    <label>Node Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Participatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>Participatory_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Participatory Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <label>Protocol</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/base/objects/OpportunityLineItem/fields/Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fee__c</fullName>
    <label>Subscription Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Product2/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The protocol associated with this product.</description>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/classes/TA_BTProduct_CheckStandardProduct.cls
public without sharing class TA_BTProduct_CheckStandardProduct implements TriggerAction.AfterInsert, TriggerAction.AfterUpdate {
    
    private class userException extends Exception {}
    @TestVisible
    private PriceBook2 standardPriceBook = [SELECT Id FROM PriceBook2 WHERE Name = 'Standard Price Book' AND IsStandard = true AND IsActive = true LIMIT 1];
    @TestVisible
    private Product2 standardSalesProduct = [SELECT Id FROM Product2 WHERE Name = 'Standard Sale' AND IsActive = true LIMIT 1];
    @TestVisible
    private boolean recordUpdateFlag = true;

    public void AfterInsert(List<BT_Product__c> newList) {
        execute(newList);
    }

    public void AfterUpdate(List<BT_Product__c> newList, List<BT_Product__c> oldList) {
        if (recordUpdateFlag) {
            execute(newList);
        }
    }
    
    private void execute(List<BT_Product__c> newList) {
        Set<Id> recordsWithProduct = new Set<Id>();
        Set<Id> recordsWithNoPriceBook = new Set<Id>();
        Set<Id> recordsWithNoProduct = new Set<Id>();
        
        //qualify
		for (BT_Product__c bt : newList) {
            if (bt.Has_Standard_Product__c) {
                recordsWithProduct.add(bt.Id);
            } else if (bt.Opportunity__c != null && bt.Opportunity__r.PriceBook2Id == null){
                recordsWithNoPriceBook.add(bt.Id);
            } else {
                recordsWithNoProduct.add(bt.Id);
            }
        }

        if(!recordsWithProduct.isEmpty()){
            updateRelatedOpportunityProduct(recordsWithProduct);
        }
        if(!recordsWithNoPriceBook.isEmpty()){
            setPriceBookOnOpportunity(recordsWithNoPriceBook);
            createOpportunityProducts(recordsWithNoPriceBook);
            updateBTProductRecords(recordsWithNoPriceBook);
        }
        if(!recordsWithNoProduct.isEmpty()){
            createOpportunityProducts(recordsWithNoProduct);
            updateBTProductRecords(recordsWithNoProduct);
        }
    }
    
    private void updateRelatedOpportunityProduct(Set<Id> recordIds) {
        List<BT_Product__c> records = [SELECT Id, 
                                       Availability_Commitment__c, 
                                       Billing_Frequency__c, 
                                       Node__r.Node_Family__c, 
                                       Quantity__c, 
                                       Participatory_Fee__c, 
                                       Opportunity__r.CloseDate, 
                                       Node_Price__c, 
                                       Sub_Total__c, 
                                       (SELECT Availability_Commitment__c , 
                                        BT_Product__c, 
                                        Billing_Frequency__c, 
                                        Had_BT_Product__c, 
                                        Hosted_Service__c, 
                                        Node_Count__c, 
                                        Participatory_Fee__c, 
                                        Quantity, 
                                        ServiceDate, 
                                        Subscription_Fee__c, 
                                        UnitPrice 
                                        FROM Opportunity_Product__r) 
                                       FROM BT_Product__c 
                                       WHERE Id IN :recordIds];
        
        List<OpportunityLineItem> opportunityProductsToUpdate = new List<OpportunityLineItem>();
        
        if (!records.isEmpty()) {
            for (BT_Product__c r : records) {
                for (OpportunityLineItem oli : r.Opportunity_Product__r) {
                    oli.Availability_Commitment__c = r.Availability_Commitment__c;
                    oli.BT_Product__c = r.Id;
                    oli.Billing_Frequency__c = r.Billing_Frequency__c;
                    oli.Had_BT_Product__c = true;
                    oli.Hosted_Service__c = r.Node__r.Node_Family__c == 'Participation' ? 'Network Participation' : 'Enterprise Node';
                    oli.Node_Count__c = r.Quantity__c;
                    oli.Participatory_Fee__c = r.Participatory_Fee__c;
                    oli.Quantity = 1;
                    oli.ServiceDate = r.Opportunity__r.CloseDate;
                    oli.Subscription_Fee__c = r.Node_Price__c;
                    oli.UnitPrice = r.Sub_Total__c;
                    
                    opportunityProductsToUpdate.add(oli);
                }
            }
        }
        if (!opportunityProductsToUpdate.isEmpty()) {
            updateOpportunityLineItems(opportunityProductsToUpdate);
        }
    }
    
    private void setPriceBookOnOpportunity (Set<Id> recordIds) {
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        Set<Id> opportunityIds = new Set<Id>();
        List<BT_Product__c> btRecords = [SELECT Id, Opportunity__c FROM BT_Product__c WHERE Id IN :recordIds];
        if (!btRecords.isEmpty()) {
            for (BT_Product__c r : btRecords) {
            	opportunityIds.add(r.Opportunity__c);
        	}
        }
        if (!opportunityIds.isEmpty()) {
            for (Opportunity o : [SELECT PriceBook2Id FROM Opportunity WHERE Id IN :opportunityIds]) {
                o.PriceBook2Id = standardPriceBook.Id;
                opportunitiesToUpdate.add(o);
            }
        }
        if (!opportunitiesToUpdate.isEmpty()) {
            updateOpportunities(opportunitiesToUpdate);
        }
    }
    
    private void createOpportunityProducts (Set<Id> recordIds) {
        List<BT_Product__c> records = [SELECT Opportunity__c,
                                       Id, 
                                       Availability_Commitment__c, 
                                       Billing_Frequency__c, 
                                       Node__r.Node_Family__c, 
                                       Quantity__c, 
                                       Participatory_Fee__c,
                                       Node__r.Protocol__r.Name,
                                       Node_Price__c, 
                                       Sub_Total__c
                                       FROM BT_Product__c 
                                       WHERE Id IN :recordIds];
        
        if (!records.isEmpty()) {
            List<OpportunityLineItem> opportunityProductsToInsert = new List<OpportunityLineItem>();
            for (BT_Product__c r : records) {
                OpportunityLineItem oli = new OpportunityLineItem();
                oli.OpportunityId = r.Opportunity__c;
                oli.Availability_Commitment__c = r.Availability_Commitment__c;
                oli.BT_Product__c = r.Id;
                oli.Billing_Frequency__c = r.Billing_Frequency__c;
                oli.Had_BT_Product__c = true;
                oli.Hosted_Service__c = r.Node__r.Node_Family__c == 'Participation' ? 'Network Participation' : 'Enterprise Node';
                oli.Node_Count__c = r.Quantity__c;
                oli.Participatory_Fee__c = r.Participatory_Fee__c;
                oli.Product2Id = standardSalesProduct.Id;
                oli.Protocol__c = r.Node__r.Protocol__r.Name;
                oli.Quantity = 1;
                oli.Subscription_Fee__c = r.Node_Price__c;
                oli.UnitPrice = r.Sub_Total__c;
                
                opportunityProductsToInsert.add(oli);
            }
            if (!opportunityProductsToInsert.isEmpty()) {
            	insertOpportunityLineItems(opportunityProductsToInsert);
        	}
        }
    }
    
    private void updateBTProductRecords (Set<Id> recordIds) {
        List<BT_Product__c> recordsToUpdate = new List<BT_Product__c>();
        for (BT_Product__c r : [SELECT Id, Has_Standard_Product__c FROM BT_Product__c WHERE Id IN :recordIds]) {
            r.Has_Standard_Product__c = true;
            recordsToUpdate.add(r);
        }
        if (!recordsToUpdate.isEmpty()) {
            recordUpdateFlag = false;
            updateBTProducts(recordsToUpdate);
        }
    }
    
    private void updateOpportunityLineItems(List<OpportunityLineItem> recordsToUpdate) {
        try {
            update recordsToUpdate;
        } catch(DMLException ex) {
            recordsToUpdate[0].addError(new userException(ex.getMessage()));
        }
    }
    
    private void insertOpportunityLineItems(List<OpportunityLineItem> recordsToInsert) {
        try {
            insert recordsToInsert;
        } catch(DMLException ex) {
            recordsToInsert[0].addError(new userException(ex.getMessage()));
        }
    }
    
    private void updateOpportunities(List<Opportunity> recordsToUpdate) {
        try {
            update recordsToUpdate;
        } catch(DMLException ex) {
            recordsToUpdate[0].addError(new userException(ex.getMessage()));
        }
    }
    
    private void updateBTProducts(List<BT_Product__c> recordsToUpdate) {
        try {
            update recordsToUpdate;
        } catch(DMLException ex) {
            recordsToUpdate[0].addError(new userException(ex.getMessage()));
        }
    }
}