src/base/objects/BT_Product__c/BT_Product__c.object-meta.xml
<CustomObject>
    <label>BT Product</label>
    <nameField>
        <label>BT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/BT_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity associated with this node.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/base/objects/BT_Product__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the sub total that is matched with sub total formula so it can be used in the opportunity rollup.</description>
    <inlineHelpText>This is will automatically populate based on the number of tokens staked and/or quantity of nodes.</inlineHelpText>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Sub_Total_Formula__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total_Formula__c</fullName>
    <description>This is the subtotal of the participation and subscription fees for this node opportunity.</description>
    <formula>IF(NOT(ISPICKVAL(Product_Type__c,&apos;Wallet-as-a-Service&apos;)),


IF(OR(ISBLANK(Node_Price__c), Node_Price__c = 0.00), 
(Quantity__c * Node__r.Base_Node_Price__c * 12), 
(Quantity__c * Node_Price__c * 12)) +   
IF(Transaction_Fee_Rewards__c = TRUE, (Avg_Transaction_Volume__c * Avg_Transaction_Fee__c) * (Tokens_Staked__c /  Avg_Total_Staked__c) * Participatory_Fee__c * 12, IF(TEXT(Node__r.Node_Family__c) = &quot;Delegation&quot;,  (Node__r.Delegation_Fee__c  * Tokens_Staked__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), IF(ISBLANK(Participatory_Fee__c), (Node__r.Participatory_Fee__c * Tokens_Staked__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), (Participatory_Fee__c * Tokens_Staked__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c)))),



IF(OR(ISBLANK(Node_Price__c), Node_Price__c = 0.00),
(Quantity__c * Node__r.Base_Node_Price__c * 12),
(Quantity__c * Node_Price__c * 12)) +
IF(Transaction_Fee_Rewards__c = TRUE, (Avg_Transaction_Volume__c * Avg_Transaction_Fee__c) * (Unique_Active_Wallet__c / Avg_Total_Staked__c) * Participatory_Fee__c * 12, IF(TEXT(Node__r.Node_Family__c) = &quot;Delegation&quot;, (Node__r.Delegation_Fee__c * Unique_Active_Wallet__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), IF(ISBLANK(Participatory_Fee__c), (Node__r.Participatory_Fee__c * Unique_Active_Wallet__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), (Participatory_Fee__c * Unique_Active_Wallet__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c))))






)</formula>
    <inlineHelpText>This is the subtotal of the participation and subscription fees for this node opportunity.</inlineHelpText>
    <label>Sub Total Formula</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Opportunity/fields/Amount_Override__c.field-meta.xml
<CustomField>
    <fullName>Amount_Override__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Don&apos;t change.</inlineHelpText>
    <label>Amount Override</label>
    <type>Checkbox</type>
</CustomField>

src/base/classes/TA_BTProduct_NodeSubUpdate.cls
// Update Opportunity Node Subtotal
public with sharing class TA_BTProduct_NodeSubUpdate 
    implements TriggerAction.BeforeUpdate, TriggerAction.BeforeInsert 
{

    boolean hasSubtotal(BT_Product__c product) {
        return (
            product.Sub_Total_Formula__c > 0 &&
            product.Opportunity__r.Amount_Override__c == true &&
            product.Opportunity__r.StageName != 'Closed Won'
        );
    }

    void updateSubtotal(List<BT_Product__c> products) {
        for (BT_Product__c product : products) {
            if (hasSubTotal(product)) {
                product.Sub_Total__c = product.Sub_Total_Formula__c;
            }
        }
    }

    public void beforeUpdate(List<BT_Product__c> products, List<BT_Product__c> old) {
        updateSubtotal(products);
    }
    
    public void beforeInsert(List<BT_Product__c> products) {
        updateSubtotal(products);
    }
}