src/base/objects/Opportunity/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <inlineHelpText>This is an estimate of the Opportunity&apos;s value. This should only be used in early stages of the pipeline.</inlineHelpText>
    <label>Estimated Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low (&lt;70k)</fullName>
            </value>
            <value>
                <fullName>Mid (&gt;70k, &lt;300k)</fullName>
            </value>
            <value>
                <fullName>High (&gt;300k)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact associate with this opportunity.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
                <isActive>false</isActive>
                <label>Node</label>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/classes/OpportunityInformationPage.cls
public class OpportunityInformationPage {
    public opportunity oppstring{get; set;}
    public OpportunityInformationPage(){
        oppstring= new opportunity();
    }
    public void Saveto(){
        opportunity opp= new opportunity();
        opp.AccountId= oppstring.AccountId;
        opp.Amount= oppstring.Amount;
        opp.CloseDate= oppstring.CloseDate;
        opp.Name= oppstring.Name;

        opp.StageName= oppstring.StageName;
        
        opp.LeadSource= oppstring.LeadSource;
        
        opp.OwnerId= oppstring.OwnerId;
        
        opp.Type= oppstring.Type;
        
        opp.Probability= oppstring.Probability;
        
        opp.Product_Type__c= oppstring.Product_Type__c;
        
        opp.Primary_Contact__c= oppstring.Primary_Contact__c;
        
        opp.RecordTypeId = oppstring.RecordTypeId;
        
        opp.Estimated_Value__c = oppstring.Estimated_Value__c;
        
        try {
            insert opp;
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.severity.CONFIRM,
                'Record successfully saved'
            ));
            oppstring.Name = null;oppstring.AccountId = null;oppstring.Amount = null;oppstring.CloseDate = null;oppstring.StageName = null;oppstring.LeadSource = null;oppstring.OwnerId = null;oppstring.Type = null;oppstring.Probability = null;oppstring.Product_Type__c = null;oppstring.RecordTypeId = null;oppstring.Estimated_Value__c = null;
        } catch (Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.severity.FATAL,
                ex.getMessage()
            ));
        }
    }

}