src/base/objects/Asset/fields/BT_Product__c.field-meta.xml
<CustomField>
    <fullName>BT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This asset&apos;s opportunity node.</description>
    <label>BT Product</label>
    <referenceTo>BT_Product__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/BT_Product__c.object-meta.xml
<CustomObject>
    <label>BT Product</label>
    <nameField>
        <label>BT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/BT_Product__c/fields/Churned__c.field-meta.xml
<CustomField>
    <fullName>Churned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this product has churned.</description>
    <label>Churned</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity associated with this node.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/base/objects/Opportunity/fields/Churned__c.field-meta.xml
<CustomField>
    <fullName>Churned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Churned</label>
    <type>Checkbox</type>
</CustomField>

src/base/classes/TA_Asset_ChurnedNotifier.cls
/******************************************************************************************************************************
* @description    : This trigger handler updates Asset related parent BT_Product and BT_Product parent's Opportunity objects
					Churned value to TRUE.
* @JIRA           : SFCC-1278
* @author         : Saurabh Sood
* @created        : 01/04/2023
* @test class     : TA_Asset_ChurnedNotifier_Test

* Modification Log :
* -----------------------------------------------------------------------------------------------------------------
* Developer                   Date(MM/DD/YYYY)       Description
******************************************************************************************************************************/
public with sharing class TA_Asset_ChurnedNotifier implements TriggerAction.AfterInsert, TriggerAction.AfterUpdate {
	@testVisible 
    private static final String STATUS_CHURNED = 'Churned';
    
    private class userException extends Exception {}
  
    /**
     * TriggerAction.AfterInsert interface implementation method
     */
    public void AfterInsert(List<Asset> newList) {
        checkAssetChurned(newList);
    }

    /**
     * TriggerAction.AfterUpdate interface implementation method
     */
    public void AfterUpdate(List<Asset> newList, List<Asset> oldList) {
        assetStatusChangedOnUpdate(newList, new Map<Id, Asset>(oldList));
    }
    
    /**
	 * Check if status flipped to 'Churned', call another methods to update BT_Product & its Opportunity churned value 
     * @param newList  List of inserted or Status changed Assets 
     */
    @testVisible 
    private static void checkAssetChurned(List<Asset> newList) {
        Set<Id> churnedAssetIds = new Set<Id>(); 
        for(Asset record: newList) {
            if(record.Status == STATUS_CHURNED) {
                churnedAssetIds.add(record.Id);
            }   
        }
        if(churnedAssetIds.size() == 0) {
            return;
        }
        assetHasChurnedRelatedUpdates(churnedAssetIds);
    }
    
    /**
	 * Asset status flipped to 'Churned' when updated, call another method to verify
     * @param newList  List of new Assets 
     * @param oldMap   Map of old Assets 
     */
    @testVisible 
    private static void assetStatusChangedOnUpdate(List<Asset> newList, Map<Id, Asset> oldMap) {
        List<Asset> changedStatusAssets = new List<Asset> (); 
        for(Asset record: newList) {
            if(record.Status != oldMap.get(record.Id).Status) {
                changedStatusAssets.add(record);
            }   
        }
        checkAssetChurned(changedStatusAssets);
    }
    
     /**
	 * Update BT_Product & its Opportunity to Churned = TRUE for Asset Status is flipped to 'Churned' 
     * @param churnedAssetIds  Set of 'Churned' Asset Ids 
     */
    @testVisible
    private static void assetHasChurnedRelatedUpdates(Set<Id> churnedAssetIds) {
        List<SObject> updateRelatedChurnedRecords = new List<SObject>(); 
        for(Asset record: [
            SELECT Id, BT_Product__r.Id, BT_Product__r.Churned__c, BT_Product__r.Opportunity__r.Id,  BT_Product__r.Opportunity__r.Churned__c 
            FROM Asset 
            WHERE Id IN: churnedAssetIds AND 
            BT_Product__c != NULL
        ]) {
            if(record.BT_Product__r.Churned__c == FALSE) {
                BT_Product__c updateBtProductRecord = new BT_Product__c(Id = record.BT_Product__r.Id, Churned__c = TRUE);
                updateRelatedChurnedRecords.add(updateBtProductRecord);
            }
            if(record.BT_Product__r.Opportunity__r.Churned__c == FALSE) {
                Opportunity updateOpportunityRecord = new Opportunity(Id = record.BT_Product__r.Opportunity__r.Id, Churned__c = TRUE);
                updateRelatedChurnedRecords.add(updateOpportunityRecord);   
            }
        }
        updateRelatedChurnedRecords(updateRelatedChurnedRecords);
    }
    
    /**
	 * Update asset related parent BT_Product & its Opportunity records
     * @param relatedRecords  List of BT_Product & Opportunity records
     */
    @testVisible
    private static void updateRelatedChurnedRecords(List<SObject> relatedRecords) {
         try {
            update relatedRecords;
        } catch(DMLException ex) {
            relatedRecords[0].addError(new userException(ex.getMessage()));
        }
    }
}