src/base/objects/Asset/fields/BT_Product__c.field-meta.xml
<CustomField>
    <fullName>BT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This asset&apos;s opportunity node.</description>
    <label>BT Product</label>
    <referenceTo>BT_Product__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Asset/fields/Churned_Reason__c.field-meta.xml
<CustomField>
    <fullName>Churned_Reason__c</fullName>
    <inlineHelpText>If the asset has churned please specify why.</inlineHelpText>
    <label>Churned Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BT Decision</fullName>
            </value>
            <value>
                <fullName>BT service</fullName>
                <isActive>false</isActive>
                <label>BT service</label>
            </value>
            <value>
                <fullName>BT Service Related - Missing Functionality / Product</fullName>
            </value>
            <value>
                <fullName>BT Service Related - Other</fullName>
            </value>
            <value>
                <fullName>BT Service Related - Price Sensitivity / Competition</fullName>
            </value>
            <value>
                <fullName>Issues with Protocol</fullName>
                <isActive>false</isActive>
                <label>Issues with Protocol</label>
            </value>
            <value>
                <fullName>Liquidating/Selling tokens</fullName>
                <isActive>false</isActive>
                <label>Liquidating/Selling tokens</label>
            </value>
            <value>
                <fullName>Non-BT Service Related - Asset Liquidation</fullName>
            </value>
            <value>
                <fullName>Non-BT Service Related - Other</fullName>
            </value>
            <value>
                <fullName>Non-BT Service Related - Protocol Issues</fullName>
            </value>
            <value>
                <fullName>Personal (non-BT service)</fullName>
                <isActive>false</isActive>
                <label>Personal (non-BT service)</label>
            </value>
            <value>
                <fullName>Platform/Service Issues</fullName>
                <isActive>false</isActive>
                <label>Platform/Service Issues</label>
            </value>
            <value>
                <fullName>Protocol issues</fullName>
                <isActive>false</isActive>
                <label>Protocol issues</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The type of product for this asset.</description>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>The protocol associated with this asset.</description>
    <label>Protocol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Protocol_List</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/BT_Product__c.object-meta.xml
<CustomObject>
    <label>BT Product</label>
    <nameField>
        <label>BT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/BT_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the account this opportunity&apos;s node is associated with.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BT Products</relationshipLabel>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>No Billing (Delegation)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Churned__c.field-meta.xml
<CustomField>
    <fullName>Churned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this product has churned.</description>
    <label>Churned</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Has_Standard_Product__c.field-meta.xml
<CustomField>
    <fullName>Has_Standard_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Standard Product</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Node__c.field-meta.xml
<CustomField>
    <fullName>Node__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The node associated with this opportunity</description>
    <label>Node</label>
    <referenceTo>Node__c</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity associated with this node.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/base/objects/BT_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Query &amp; Transact</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
            <value>
                <fullName>Participate</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The number of nodes</description>
    <label>Node Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Tokens_Staked__c.field-meta.xml
<CustomField>
    <fullName>Tokens_Staked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of tokens staked for this protocol</description>
    <inlineHelpText>This value refers to either Tokens Staked OR Annual Transacting Users for Coinbase Pay opportunities.</inlineHelpText>
    <label>Tokens Staked/Annual Users</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Node__c/Node__c.object-meta.xml
<CustomObject>
    <description>This is the given node offering of a given protocol.</description>
    <label>Node</label>
    <nameField>
        <label>Node</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/objects/Node__c/fields/Base_Node_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Node_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the standard price we charge for this node.</description>
    <label>Base Node Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Node__c/fields/Node_Family__c.field-meta.xml
<CustomField>
    <fullName>Node_Family__c</fullName>
    <description>This is the type of node in the format {Protocol-Node Type}</description>
    <inlineHelpText>{Protocol-Node Type}</inlineHelpText>
    <label>Node Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Node__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Protocol one which this type of node is run.</description>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Churned__c.field-meta.xml
<CustomField>
    <fullName>Churned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Churned</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
                <isActive>false</isActive>
                <label>Node</label>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Product2/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The protocol associated with this product.</description>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/globalValueSets/Protocol_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acala</fullName>
    </customValue>
    <customValue>
        <fullName>Algorand</fullName>
    </customValue>
    <customValue>
        <fullName>Aptos</fullName>
    </customValue>
    <customValue>
        <fullName>Avalanche</fullName>
    </customValue>
    <customValue>
        <fullName>Axelar</fullName>
    </customValue>
    <customValue>
        <fullName>Binance Smart Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin SV</fullName>
    </customValue>
    <customValue>
        <fullName>Cardano</fullName>
    </customValue>
    <customValue>
        <fullName>Celo</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmos</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto.com</fullName>
    </customValue>
    <customValue>
        <fullName>Decred</fullName>
    </customValue>
    <customValue>
        <fullName>Diem</fullName>
    </customValue>
    <customValue>
        <fullName>Dogecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Edgeware</fullName>
    </customValue>
    <customValue>
        <fullName>EOS</fullName>
    </customValue>
    <customValue>
        <fullName>Eth2</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum 1.X</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Evmos</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Helium</fullName>
    </customValue>
    <customValue>
        <fullName>Karura</fullName>
    </customValue>
    <customValue>
        <fullName>Keep</fullName>
    </customValue>
    <customValue>
        <fullName>Kusama</fullName>
    </customValue>
    <customValue>
        <fullName>Litecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Livepeer</fullName>
    </customValue>
    <masterLabel>Protocol List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/classes/TA_Asset_ChurnedNotifier_Test.cls
@isTest
private with sharing class TA_Asset_ChurnedNotifier_Test {
  private static final String STATUS_CHURNED = TA_Asset_ChurnedNotifier.STATUS_CHURNED;

  private static String statusNotChurned {
    get {
      if (statusNotChurned == null) {
        String status;
        for (
          Schema.PicklistEntry entryObj : Asset.Status.getDescribe()
            .getPicklistValues()
        ) {
          status = entryObj.getValue();
          if (status != TA_Asset_ChurnedNotifier.STATUS_CHURNED) {
            statusNotChurned = status;
            break;
          }
        }
      }
      return statusNotChurned;
    }
    set;
  }

  private static String churnedReason {
    get {
      if (churnedReason == null) {
        for (
          Schema.PicklistEntry entryObj : Asset.Churned_Reason__c.getDescribe()
            .getPicklistValues()
        ) {
          churnedReason = entryObj.getValue();
          break;
        }
      }
      return churnedReason;
    }
    set;
  }

  @testSetup
  static void setup() {
    Pricebook2 standardPricebook = new Pricebook2(
      Id = Test.getStandardPricebookId(),
      IsActive = true
    );
    update standardPricebook;

    Product2 product = new Product2(Name = 'Standard Sale', IsActive = true);
    insert product;

    PricebookEntry pbe = new PricebookEntry(
      Pricebook2Id = standardPricebook.Id,
      Product2Id = product.Id,
      isActive = true,
      UnitPrice = 1.00
    );
    insert pbe;
  }

  @isTest
  private static void checkAssetStatusIsNotChurned_Insert() {
    Asset record = new Asset(Status = statusNotChurned);
    TA_Asset_ChurnedNotifier obj = new TA_Asset_ChurnedNotifier();

    Test.startTest();
    obj.AfterInsert(new List<Asset>{ record });
    Integer issuedSOQL = Limits.getQueries();
    Integer issueDML = Limits.getDmlStatements();
    Test.stopTest();

    System.assertEquals(
      0,
      issuedSOQL,
      'A SOQL should not be performed on parent record, When Asset status is not "' +
      STATUS_CHURNED +
      '"'
    );

    System.assertEquals(
      0,
      issueDML,
      'A DML operation should not be performed to update the parent record, When the Asset status is not "' +
      STATUS_CHURNED +
      '"'
    );
  }

  @isTest
  private static void checkAssetStatusIsChurnedWithoutBTProduct_Insert() {
    Id assetId = fflib_IDGenerator.generate(Asset.SObjectType);
    Asset record = new Asset(Id = assetId, Status = STATUS_CHURNED);
    TA_Asset_ChurnedNotifier obj = new TA_Asset_ChurnedNotifier();

    Test.startTest();
    obj.AfterInsert(new List<Asset>{ record });
    Integer issuedSOQL = Limits.getQueries();
    Integer issueDML = Limits.getDmlStatements();
    Test.stopTest();

    System.assertEquals(
      1,
      issuedSOQL,
      'When Asset status is "' +
      STATUS_CHURNED +
      '" System should performed SOQL to Update Parent BT_Product as Churned "' +
      STATUS_CHURNED +
      '"'
    );

    System.assertEquals(
      0,
      issueDML,
      'Since Parent BT_Product is not present in Asset, it should not perform any updates to parent records'
    );
  }

  @isTest
  private static void checkAssetStatusChangedToNotChurned_Update() {
    Id assetId = fflib_IDGenerator.generate(Asset.SObjectType);
    Asset newRecord = new Asset(Id = assetId, Status = statusNotChurned);
    Asset oldRecord = newRecord.clone(
      true /*preserved ids*/,
      false,
      false,
      false
    );
    oldRecord.Status = STATUS_CHURNED;

    TA_Asset_ChurnedNotifier obj = new TA_Asset_ChurnedNotifier();

    Test.startTest();
    obj.AfterUpdate(new List<Asset>{ newRecord }, new List<Asset>{ oldRecord });
    Integer issuedSOQL = Limits.getQueries();
    Integer issueDML = Limits.getDmlStatements();
    Test.stopTest();

    System.assertEquals(
      0,
      issuedSOQL,
      'A SOQL should not be performed on parent record, When Asset status not changed to "' +
      STATUS_CHURNED +
      '"'
    );

    System.assertEquals(
      0,
      issueDML,
      'A DML operation should not be performed to update the parent record, When the Asset status is not changed to "' +
      STATUS_CHURNED +
      '"'
    );
  }

  @isTest
  private static void assetChangedToChurnedWithBTProduct_Insert() {
    String nodeString = 'Node';
    Account testAccount = TestDataHelper.getAccounts(1, true)[0];
    Contact testContact = TestDataHelper.getContacts(
      testAccount.Id,
      1,
      true
    )[0];

    Opportunity testOpportunity = TestDataHelper.getOpportunities(
      testAccount.Id,
      1,
      false
    )[0];
    testOpportunity.Pricebook2Id = Test.getStandardPricebookId();
    insert testOpportunity;

    List<Opportunity> queriedOppies = [SELECT Id, Churned__c FROM Opportunity];
    System.assertEquals(
      1,
      queriedOppies.size(),
      'System should create only one Opportunity record'
    );

    System.assertEquals(
      false,
      queriedOppies[0].Churned__c,
      'On Insert Opportunity should set Churned value as FALSE'
    );

    Protocol__c protocol = new Protocol__c(Name = 'test');
    insert protocol;

    Node__c node = new Node__c(
      Protocol__c = protocol.Id,
      Node_Family__c = nodeString,
      Base_Node_Price__c = 1
    );
    insert node;

    BT_Product__c testBtProductRecord = new BT_Product__c();
    testBtProductRecord.Opportunity__c = queriedOppies[0].Id;
    testBtProductRecord.Account__c = testAccount.Id;
    testBtProductRecord.Node__c = node.Id;
    testBtProductRecord.Quantity__c = 1;
    testBtProductRecord.Churned__c = false;
    testBtProductRecord.Billing_Frequency__c = 'Monthly';
    testBtProductRecord.Has_Standard_Product__c = true;
    testBtProductRecord.Tokens_Staked__c = 5;
    insert testBtProductRecord;

    Test.startTest();
    Asset record = new Asset(
      Name = 'testAsset',
      AccountId = testAccount.Id,
      ContactId = testContact.Id,
      Status = STATUS_CHURNED,
      Churned_Reason__c = churnedReason,
      BT_Product__c = testBtProductRecord.Id,
      UsageEndDate = System.today().addDays(-1),
      Protocol__c = 'Acala',
      Product_Type__c = nodeString
    );
    insert record;
    Test.stopTest();

    List<Asset> assets = [
      SELECT
        Id,
        BT_Product__r.Id,
        BT_Product__r.Churned__c,
        BT_Product__r.Opportunity__r.Id,
        BT_Product__r.Opportunity__r.Churned__c
      FROM Asset
    ];

    System.assertEquals(
      1,
      assets.size(),
      'System should create only one asset record'
    );

    System.assertEquals(
      testBtProductRecord.Id,
      assets[0].BT_Product__r.Id,
      'The Asset parent BT_Product record should be the same as the BT_Product record inserted in the test'
    );

    System.assertEquals(
      true,
      assets[0].BT_Product__r.Churned__c,
      'When Asset Status set as "' +
      STATUS_CHURNED +
      '", it should update parent Asset.BT_Product object field "' +
      STATUS_CHURNED +
      '" to true'
    );

    System.assertEquals(
      testOpportunity.Id,
      assets[0].BT_Product__r.Opportunity__r.Id,
      'The Asset parent BT_Product parent Opportunity should be the same as the Opportunity record inserted in the test'
    );

    System.assertEquals(
      true,
      assets[0].BT_Product__r.Churned__c,
      'When Asset Status set as "' +
      STATUS_CHURNED +
      '", it should update parent Asset.BT_Product__r.Opportunity__r object field "' +
      STATUS_CHURNED +
      '" to true'
    );
  }

  @isTest
  private static void sObjectDMLException_test() {
    Id fakeBtProductId = fflib_IDGenerator.generate(BT_Product__c.SObjectType);
    BT_Product__c dmlExceptionRecordToUpdate = new BT_Product__c(
      Id = fakeBtProductId,
      Churned__c = true
    );
    Exception expectedException;

    try {
      TA_Asset_ChurnedNotifier.updateRelatedChurnedRecords(
        new List<SObject>{ dmlExceptionRecordToUpdate }
      );
    } catch (DMLException ex) {
      expectedException = ex;
    }
    System.assertEquals(
      null,
      expectedException,
      'When updating a related record, the system should throw an exception if there is an exception'
    );
  }
}