src/base/objects/Asset/fields/BT_Product__c.field-meta.xml
<CustomField>
    <fullName>BT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This asset&apos;s opportunity node.</description>
    <label>BT Product</label>
    <referenceTo>BT_Product__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/BT_Product__c.object-meta.xml
<CustomObject>
    <label>BT Product</label>
    <nameField>
        <label>BT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/BT_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the account this opportunity&apos;s node is associated with.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BT Products</relationshipLabel>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>No Billing (Delegation)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/BT_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity associated with this node.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Nodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/base/objects/BT_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The number of nodes</description>
    <label>Node Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the sub total that is matched with sub total formula so it can be used in the opportunity rollup.</description>
    <inlineHelpText>This is will automatically populate based on the number of tokens staked and/or quantity of nodes.</inlineHelpText>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Sub_Total_Formula__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total_Formula__c</fullName>
    <description>This is the subtotal of the participation and subscription fees for this node opportunity.</description>
    <formula>IF(NOT(ISPICKVAL(Product_Type__c,&apos;Wallet-as-a-Service&apos;)),


IF(OR(ISBLANK(Node_Price__c), Node_Price__c = 0.00), 
(Quantity__c * Node__r.Base_Node_Price__c * 12), 
(Quantity__c * Node_Price__c * 12)) +   
IF(Transaction_Fee_Rewards__c = TRUE, (Avg_Transaction_Volume__c * Avg_Transaction_Fee__c) * (Tokens_Staked__c /  Avg_Total_Staked__c) * Participatory_Fee__c * 12, IF(TEXT(Node__r.Node_Family__c) = &quot;Delegation&quot;,  (Node__r.Delegation_Fee__c  * Tokens_Staked__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), IF(ISBLANK(Participatory_Fee__c), (Node__r.Participatory_Fee__c * Tokens_Staked__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), (Participatory_Fee__c * Tokens_Staked__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c)))),



IF(OR(ISBLANK(Node_Price__c), Node_Price__c = 0.00),
(Quantity__c * Node__r.Base_Node_Price__c * 12),
(Quantity__c * Node_Price__c * 12)) +
IF(Transaction_Fee_Rewards__c = TRUE, (Avg_Transaction_Volume__c * Avg_Transaction_Fee__c) * (Unique_Active_Wallet__c / Avg_Total_Staked__c) * Participatory_Fee__c * 12, IF(TEXT(Node__r.Node_Family__c) = &quot;Delegation&quot;, (Node__r.Delegation_Fee__c * Unique_Active_Wallet__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), IF(ISBLANK(Participatory_Fee__c), (Node__r.Participatory_Fee__c * Unique_Active_Wallet__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c), (Participatory_Fee__c * Unique_Active_Wallet__c * Node__r.Protocol__r.Inflation_Rate__c * Node__r.Protocol__r.Price__c))))






)</formula>
    <inlineHelpText>This is the subtotal of the participation and subscription fees for this node opportunity.</inlineHelpText>
    <label>Sub Total Formula</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/BT_Product__c/fields/Tokens_Staked__c.field-meta.xml
<CustomField>
    <fullName>Tokens_Staked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of tokens staked for this protocol</description>
    <inlineHelpText>This value refers to either Tokens Staked OR Annual Transacting Users for Coinbase Pay opportunities.</inlineHelpText>
    <label>Tokens Staked/Annual Users</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Opportunity/fields/Amount_Override__c.field-meta.xml
<CustomField>
    <fullName>Amount_Override__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Don&apos;t change.</inlineHelpText>
    <label>Amount Override</label>
    <type>Checkbox</type>
</CustomField>

src/base/classes/TA_BTProduct_NodeSubUpdateTest.cls
@istest
public with sharing class TA_BTProduct_NodeSubUpdateTest {
    static final String ASSET = 'asset';
    static final String STAGE = 'stage';
    static final String ACCOUNT_OVERRIDE = 'override';

    static BT_Product__c getProduct(Map<String, Object> params) {
        return  (BT_Product__c) fflib_ApexMocksUtils.setReadOnlyFields(
            new BT_Product__c(
                Name = (string)params.get(ASSET),
                Account__c = fflib_IDGenerator.generate(Account.SObjecttype),
                Billing_Frequency__c = 'Monthly',
                Quantity__c = 1.0,
                Tokens_Staked__c = 5,
                Opportunity__r = new Opportunity(
                    Id = fflib_IDGenerator.generate(Opportunity.SObjecttype),
                    Name = params.get('asset') + ' Deal',
                    StageName = (string) params.get(STAGE),
                    CloseDate = System.today().addDays(30),
                    Amount_Override__c = (boolean) params.get(ACCOUNT_OVERRIDE)
                )
            ), 
            BT_Product__c.class,
            new Map<SObjectField, Object> {
                BT_Product__c.Sub_Total_Formula__c  => 10
            }
        );
    }

    static List<BT_Product__c> copy(List<BT_Product__c> source) {
        List<BT_Product__c> target = new List<BT_Product__c>();

        for (BT_Product__c product : source) {
            BT_Product__c element = product.clone();
            target.add(element);
        }

        return target;
    }

    @isTest
    static void verify() {

        // We're only setting up the fields and relationships 
        // we need for the unit test

        BT_Product__c dotLineItem = getProduct(new Map<String, Object> {
            ASSET => 'DOT',
            STAGE => 'Prospecting',
            ACCOUNT_OVERRIDE => true
        });

        BT_Product__c ethLineItem = getProduct(new Map<String, Object> {
            ASSET => 'ETH',
            STAGE => 'Prospecting',
            ACCOUNT_OVERRIDE => false
        });


        BT_Product__c xtzLineItem = getProduct(new Map<String, Object> {
            ASSET => 'XTZ',
            STAGE => 'Closed Won',
            ACCOUNT_OVERRIDE => true
        });
        
        List<BT_Product__c> products = new List<BT_Product__c> {
            dotLineItem, ethLineItem, xtzLineItem
        };

        TA_BTProduct_NodeSubUpdate action = new TA_BTProduct_NodeSubUpdate();
        action.beforeInsert(products);

        System.assertEquals(
            10, dotLineItem.Sub_Total__c, 
            'Product with greater than 0 subtotal not updated'
        );
        System.assertEquals(
            null, ethLineItem.Sub_Total__c, 
            'Product with account override not set updated'
        );
        System.assertEquals(
            null, xtzLineItem.Sub_Total__c, 
            'Totals for closed won opportunities should not be updated'
        );

        List<BT_Product__c> newProducts = copy(products);

        BT_Product__c newDotLineItem = (BT_Product__c) fflib_ApexMocksUtils.setReadOnlyFields(
            newProducts[0], BT_Product__c.class,
            new Map<SObjectField, Object> {
                BT_Product__c.Sub_Total_Formula__c  => 0
            }
        );

        BT_Product__c newEthLineItem = newProducts[1];
        newEthLineItem.Opportunity__r.Amount_Override__c = true;
        
        BT_Product__c newXtzLineItem = newProducts[2];
        newXtzLineItem.Opportunity__r.StageName = 'Prospecting';

        action.beforeUpdate(newProducts, products);

        System.assertEquals(
            10, newDotLineItem.Sub_Total__c, 
            'It should still be 10 because the formula value is 0'
        );
        System.assertEquals(
            10, newEthLineItem.Sub_Total__c, 
            'Should update now that Account Override is set to true'
        );
        System.assertEquals(
            10, newXtzLineItem.Sub_Total__c, 
            'Stage is back to prospecting (not a valid transition) by should be 10 now'
        );

    }
}