src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/objects/Protocol_Interest__c/Protocol_Interest__c.object-meta.xml
<CustomObject>
    <label>Protocol Interest</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Protocol Interest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/Protocol_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Protocol Interests</relationshipLabel>
    <relationshipName>Protocol_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Protocol_Interest__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Protocol Interests</relationshipLabel>
    <relationshipName>Protocol_Interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/base/classes/ProtocolController.cls
public with sharing class ProtocolController {
    @AuraEnabled
    public static List<Protocol__c> getProtocolRecord() {
        return [Select Id, Name from Protocol__c];
    }
    
    @AuraEnabled
    public static List<Protocol_Interest__c> getSelectedProtocol(String leadId) {
        return [Select Id, Protocol__c from Protocol_Interest__c where Lead__c = :leadId];
    }
    
    @AuraEnabled
    public static void updateProtocol(List<String> protocolIds, String leadId) {
        System.debug('protocolIds are ' + protocolIds);
        
        Set<Id> existingProtocolInterestList = new Set<Id>();
        Set<Id> removeProtocolInterestSet = new Set<Id>();
        Set<Id> addProtocolInterestSet = new Set<Id>();
        for(Protocol_Interest__c protocolInterest : [Select Protocol__c from Protocol_Interest__c where Lead__c = :leadId]) {
            existingProtocolInterestList.add(protocolInterest.Protocol__c); 
        }
        
        removeProtocolInterestSet  = existingProtocolInterestList.clone();
        
        List<Protocol_Interest__c > protocolInterestList = new List<Protocol_Interest__c >();
        for(String protocol: protocolIds){
            addProtocolInterestSet.add(protocol);
            
            if(!existingProtocolInterestList.contains(protocol)){
                Protocol_Interest__c pc = new Protocol_Interest__c();
                pc.Lead__c = leadId;
                pc.Protocol__c  = protocol;
                protocolInterestList.add(pc);
            }
        }
        removeProtocolInterestSet.removeAll(addProtocolInterestSet);
        
        Delete [Select id from Protocol_Interest__c where Protocol__c IN: removeProtocolInterestSet and Lead__c = :leadId];
        insert protocolInterestList;
    }    
}