src/base/objects/KeyValue__mdt/KeyValue__mdt.object-meta.xml
<CustomObject>
    <label>KeyValue</label>
    <pluralLabel>KeyValues</pluralLabel>
</CustomObject>

src/base/objects/KeyValue__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/KeyValue__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/base/objects/KeyValue__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/base/objects/KeyValue__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/base/objects/Opportunity/fields/IsClosedDate_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>IsClosedDate_Current_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFCC-1355: if ClosedDate lies under current year, flow auto update this field to checked. If ClosedDate does not lies in current year by next year 1 Jan, auto schedule flow update this field to unchecked.</description>
    <label>ClosedDate Current Year?</label>
    <type>Checkbox</type>
</CustomField>

src/base/classes/ResetYtdRevenueBatch.cls
/******************************************************************************************************************************
* @description    : This batch runs every year on January 1 to flip IsClosedDate_Current_Year__c to FALSE. 
					In the Parent Account record, it recalculates the roll up summary of CurrentYEAR Opportunities Amount
* @JIRA           : SFCC-1397
* @author         : Saurabh Sood
* @created        : 12/01/2022
* @test class     : ResetYtdRevenueBatch_Test

* Modification Log :
* -----------------------------------------------------------------------------------------------------------------
* Developer                   Date(MM/DD/YYYY)       Description
******************************************************************************************************************************/
public class ResetYtdRevenueBatch implements Database.Batchable<sObject>, Database.Stateful  {
    private final String header = 'Record Id, Error Message \n';
    @testVisible private final static String NAMESPACE = 'YTDRevenueEmails';

    private String finalstr = header ;
    private final String QUERY;
   
	public ResetYtdRevenueBatch(String q){
		 QUERY = q; 
	}
    /**
     * Get emailAddresses from the keyvalue metadata 
     */
    @testVisible private static Map<String,String> emailAddresses {
        get {
            if(emailAddresses == null) {
                emailAddresses = new Map<String,String>();
                for(KeyValue__mdt mtd: [SELECT Key__c, Value__c 
                                        FROM KeyValue__mdt 
                                        WHERE Namespace__c =: NAMESPACE 
                                        AND IsActive__c = TRUE]) {
                  emailAddresses.put(mtd.Key__c, mtd.Value__c);  
                }
            }
            return emailAddresses;
        }
        private set;
    }
    
    /**
     * Get orgWideFromEmailId based on fromEmailAddress from the keyvalue metadata 
     */
    @testVisible private static Id orgWideFromEmailId {
        get {
            if(orgWideFromEmailId == NULL && emailAddresses.get('fromAddress') != NULL) {
               orgWideFromEmailId = [SELECT Id 
                                     FROM OrgWideEmailAddress 
                                     WHERE Address =: emailAddresses.get('fromAddress')
                                    ]?.Id;            
            }
            return orgWideFromEmailId;
        }
        private set;
    }


    /**
    *   Returns a List of Opportunities whose IsClosedDate_Current_Year__c = TRUE and CloseDate is LAST_YEAR
    */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(QUERY); 
    }

	/**
     * Update Opportunity.IsClosedDate_Current_Year__c from TRUE to FALSE & store failed record with error message
     */
    public void execute(Database.BatchableContext bc, List<Opportunity> oppyList) {
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>(); 
        for(Opportunity opp: oppyList) {
           	opp.IsClosedDate_Current_Year__c = FALSE;
            opportunitiesToUpdate.add(opp);
        }

        List<Database.SaveResult> saveResultList  = Database.update(opportunitiesToUpdate,false);
        
        Integer recordId = 0;
        for (Database.SaveResult saveResult : saveResultList) {
            if (!saveResult.isSuccess()) {
                string recordErrorString = '"'+opportunitiesToUpdate[recordId].id+'","'+saveResult.getErrors()[0].getMessage()+'"\n';
       			finalstr += recordErrorString;
            }
            recordId++;
        }
    }
    public void finish(Database.BatchableContext bc) {
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        email.setSubject('ResetYtdRevenueBatch Failed Opportunities');
        email.setOrgWideEmailAddressId(orgWideFromEmailId); 
        email.setToAddresses(new list<string>((List<String>)emailAddresses.get('toAddress').split(',')));
        email.setPlainTextBody('Hi Team,\nPlease review the attachment to see failed opportunity records!');
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{getCsvAttachment(finalstr)});

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }
    
    /**
     * Build Opportunity failed records as CSV attachment
     * @param failedRecords  List of failed records from the UPDATE Event
     * @return  CSV attachment file
     */
    private static Messaging.EmailFileAttachment getCsvAttachment(String failedRecords) {
        Messaging.EmailFileAttachment csvAttachment = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(failedRecords);
        csvAttachment.setFileName('FailedOpportunities.csv');
        csvAttachment.setBody(csvBlob);
        return csvAttachment;
    }
   
}