src/base/objects/Lead/fields/Country_Attributes__c.field-meta.xml
<CustomField>
    <fullName>Country_Attributes__c</fullName>
    <label>Country Attributes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incorporation</fullName>
            </value>
            <value>
                <fullName>Business Operations</fullName>
            </value>
            <value>
                <fullName>Customer Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

src/base/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>[SFCC-396] Lead Region based on Countries of Incorporation</description>
    <inlineHelpText>Region is based on Countries of Incorporation. If multiple countries from different Regions are selected, then Region is Global.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/base/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <description>[SFCC-396] Region picklist for Lead, Account and Opportunity</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/base/classes/TA_Lead_PopulateCountryCodeAndRegion.cls
public without sharing class TA_Lead_PopulateCountryCodeAndRegion implements TriggerAction.BeforeInsert, TriggerAction.BeforeUpdate {
	public void beforeInsert(List<Lead> newList) {
        handleCountryCodesAndRegion(newList);
    }
    
    public void beforeUpdate(List<Lead> newList, List<Lead> oldList) {
        Map<Id, Lead> oldMap = new Map<Id, Lead>(oldList);
        handleCountryCodesAndRegion(newList, oldMap);
    }
    
    public static void handleCountryCodesAndRegion(List<Lead> newLeads) {
        for (Lead lead : newLeads) {
            if(String.isNotEmpty(lead.Location__c)){
                updateLead(lead);
            }
            if (String.isNotEmpty(lead.Countries_of_Incorporation__c)) {
                CountryCodeCalculator.setCountryCodesAndRegion(lead);
            }
        }
    }
    
    public static void handleCountryCodesAndRegion(List<Lead> newLeads, Map<Id, Lead> oldLeads) {
        for (Lead lead : newLeads) {
            if(String.isNotEmpty(lead.Location__c)){
                updateLead(lead);
            }
            if (String.isEmpty(lead.Countries_of_Incorporation__c)) {
                lead.Country_Codes__c = null;
                lead.Region__c = null;
            } else {
                Lead oldLead = oldLeads.get(lead.Id);

                if (lead.Countries_of_Incorporation__c != oldLead.Countries_of_Incorporation__c) {
                    CountryCodeCalculator.setCountryCodesAndRegion(lead);
                }
            }
        }
    }
    
    public static void updateLead (Lead l) {
        l.Countries_of_Incorporation__c = l.Location__c;
        l.Country_Attributes__c = 'Incorporation';
    }
}