src/base/objects/Lead/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Segment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Lead_Close_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lead_Close_Reason__c</fullName>
    <label>Lead Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Alternative / Competitor</fullName>
            </value>
            <value>
                <fullName>Incorrect / Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Spam / Phishing</fullName>
            </value>
            <value>
                <fullName>Other Coinbase</fullName>
            </value>
            <value>
                <fullName>Doesn&apos;t want to work with Coinbase</fullName>
            </value>
            <value>
                <fullName>Prioritization</fullName>
            </value>
            <value>
                <fullName>Project Paused/Discontinued</fullName>
            </value>
            <value>
                <fullName>Quid Pro-Quo</fullName>
            </value>
            <value>
                <fullName>Technical Blocker</fullName>
            </value>
            <value>
                <fullName>Unsupported Protocol</fullName>
            </value>
            <value>
                <fullName>Unresponsive (60 days+)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Limited Engagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

src/base/globalValueSets/Customer_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Coinbase Team</fullName>
    </customValue>
    <customValue>
        <fullName>Startup</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Service - Traditional</fullName>
        <isActive>false</isActive>
        <label>Financial Service - Traditional</label>
    </customValue>
    <customValue>
        <fullName>Financial Service - Crypto Native</fullName>
        <isActive>false</isActive>
        <label>Financial Service - Crypto Native</label>
    </customValue>
    <customValue>
        <fullName>Startups</fullName>
        <isActive>false</isActive>
        <label>Startups</label>
    </customValue>
    <masterLabel>Customer Segment</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other (Unspecified)</fullName>
    </customValue>
    <customValue>
        <fullName>Delegate</fullName>
    </customValue>
    <customValue>
        <fullName>Participate</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange &amp; Pro APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Sign in with Coinbase</fullName>
    </customValue>
    <customValue>
        <fullName>Prime APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Rosetta</fullName>
    </customValue>
    <customValue>
        <fullName>Query &amp; Transact</fullName>
    </customValue>
    <customValue>
        <fullName>Staking</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet-as-a-Service</fullName>
    </customValue>
    <customValue>
        <fullName>NFT</fullName>
    </customValue>
    <customValue>
        <fullName>Data Indexers</fullName>
        <isActive>false</isActive>
        <label>Data Indexers</label>
    </customValue>
    <customValue>
        <fullName>Node</fullName>
        <isActive>false</isActive>
        <label>Node</label>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

src/base/classes/LeadInactivityScheduleJobTest.cls
/**
 * @description       : 
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 01-05-2023
 * @last modified by  : Lavanya Tangati
**/
@isTest
private class LeadInactivityScheduleJobTest {
    @testSetup
    static void setup() {
        list<Lead> testLead = new list<Lead>();
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Standard Lead').getRecordTypeId();
        for(integer i = 0 ; i < 4 ; i++){
            Lead l = new Lead();
            l.firstName = 'TestFirst';
            l.LastName = 'Last' +string.valueOf(i);
            l.Email = 'test'+string.valueOf(i)+'@nomail.invalid';
            l.Company = 'Test Company'+string.valueOf(i);
            l.LeadSource = 'Partner';
            l.Customer_Segment__c = 'Individual';
            l.Product_Interest__c = 'Participate';
            l.RecordTypeId = recordTypeId;
            testLead.add(l);
        }
        insert testLead;
        //Test.loadData(Lead.sObjectType, 'InactiveLeadTest');
    }
    
    @isTest 
    static void verifyScheduleJob() {
        LeadInactivityScheduleJob schJob = new LeadInactivityScheduleJob(5);
        
        Test.startTest();
        System.schedule('Test_LeadInactivityScheduleJob', '0 0 * * * ?', schJob);
        Test.stopTest();
    }
    
    @isTest
    static void verifyInactiveLeadNotice() {
        Test.startTest();
        BatchLeadInactiveNotification inactiveNoticeJob = new BatchLeadInactiveNotification();
        Database.executeBatch(inactiveNoticeJob, 5);
        Test.stopTest();
    }
    
    @isTest
    static void verifyInactiveLeadClosing() {
        Test.startTest();
        BatchLeadInactiveClosing inactiveClosingJob = new BatchLeadInactiveClosing();
        Database.executeBatch(inactiveClosingJob, 5);
        Test.stopTest();
        
        Lead lead = [SELECT Id, Status, Lead_Close_Reason__c FROM Lead LIMIT 1];
        
        System.assertEquals('Open', lead.Status);
        System.assertEquals(null, lead.Lead_Close_Reason__c);
    }
}