src/base/objects/Lead/fields/Protocol_Interest__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Interest__c</fullName>
    <description>This is the Lead&apos;s main protocol of interest.</description>
    <label>Protocol Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Protocol_List</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/objects/Protocol_Interest__c/Protocol_Interest__c.object-meta.xml
<CustomObject>
    <label>Protocol Interest</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Protocol Interest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/Protocol_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Protocol Interests</relationshipLabel>
    <relationshipName>Protocol_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Protocol_Interest__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Protocol Interests</relationshipLabel>
    <relationshipName>Protocol_Interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/base/globalValueSets/Protocol_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acala</fullName>
    </customValue>
    <customValue>
        <fullName>Algorand</fullName>
    </customValue>
    <customValue>
        <fullName>Aptos</fullName>
    </customValue>
    <customValue>
        <fullName>Avalanche</fullName>
    </customValue>
    <customValue>
        <fullName>Axelar</fullName>
    </customValue>
    <customValue>
        <fullName>Binance Smart Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin SV</fullName>
    </customValue>
    <customValue>
        <fullName>Cardano</fullName>
    </customValue>
    <customValue>
        <fullName>Celo</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmos</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto.com</fullName>
    </customValue>
    <customValue>
        <fullName>Decred</fullName>
    </customValue>
    <customValue>
        <fullName>Diem</fullName>
    </customValue>
    <customValue>
        <fullName>Dogecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Edgeware</fullName>
    </customValue>
    <customValue>
        <fullName>EOS</fullName>
    </customValue>
    <customValue>
        <fullName>Eth2</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum 1.X</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Evmos</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Helium</fullName>
    </customValue>
    <customValue>
        <fullName>Karura</fullName>
    </customValue>
    <customValue>
        <fullName>Keep</fullName>
    </customValue>
    <customValue>
        <fullName>Kusama</fullName>
    </customValue>
    <customValue>
        <fullName>Litecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Livepeer</fullName>
    </customValue>
    <masterLabel>Protocol List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/classes/ProtocolControllerTest.cls
@isTest
private class ProtocolControllerTest {
    @testSetup
    static void setup() {
		TestDataHelper.getStandardLeads(1, true);
        
        Protocol__c protocol = new Protocol__c();
        protocol.name = 'test';
        insert protocol;
    }
    
    @isTest 
    static void testProtocolControllerMethods() {
        String leadId = [SELECT Id FROM Lead LIMIT 1].Id;
        
        List<String> protocolIds = new List<String>();
        String protocolId = [SELECT Id FROM Protocol__c].Id;
        protocolIds.add(protocolId);
        
        Test.startTest();
        ProtocolController.getProtocolRecord();
        ProtocolController.getSelectedProtocol(leadId); 
        ProtocolController.updateProtocol(protocolIds, leadId);
        Test.stopTest();
        
        Protocol_Interest__c protocolInterest = [SELECT Protocol__c FROM Protocol_Interest__c];
        System.assertEquals(protocolId, protocolInterest.Protocol__c);
    }
    
    @isTest
    static void testAddingProtocols() {
        Id leadId = [SELECT Id FROM Lead LIMIT 1].Id;
        
        Protocol__c testProtocol1 = new Protocol__c();
        testProtocol1.name = 'Test1';
        
        Protocol__c testProtocol2 = new Protocol__c();
        testProtocol2.name = 'Test2';
        
        Protocol__c testProtocol3 = new Protocol__c();
        testProtocol3.name = 'Test3';
        
        insert new List<Protocol__c>{testProtocol1, testProtocol2, testProtocol3};
        
        Test.startTest();
        List<String> protocolIds = new List<String>{testProtocol1.Id, testProtocol2.Id};
        ProtocolController.updateProtocol(protocolIds, leadId);
        
        protocolIds = new List<String>{testProtocol1.Id, testProtocol3.Id};
        ProtocolController.updateProtocol(protocolIds, leadId);
        Test.stopTest();
        
        List<Protocol_Interest__c> protocolInterests = [SELECT Protocol__c FROM Protocol_Interest__c WHERE Lead__c = :leadId];
        
        Set<Id> leadProtocolIds = new Set<Id>();
        for (Protocol_Interest__c pi : protocolInterests) {
            leadProtocolIds.add(pi.Protocol__c);
        }
        
        System.assert(leadProtocolIds.contains(testProtocol1.Id));
        System.assert(!leadProtocolIds.contains(testProtocol2.Id));
        System.assert(leadProtocolIds.contains(testProtocol3.Id));
    }
}