src/base/objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This account&apos;s main billing contact.</description>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Account/fields/Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Country_Codes__c</fullName>
    <label>Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Codes</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/CS_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>CS_Account_Status__c</fullName>
    <description>SFCC-790 - This picklist value displays if an Account is Active, Inactive, Churned or Not Onboarded</description>
    <label>CS Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Churned</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Not Onboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/CS_Owner__c.field-meta.xml
<CustomField>
    <fullName>CS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This account&apos;s CS owner</description>
    <inlineHelpText>Engagement Manager</inlineHelpText>
    <label>EM Primary Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Number_of_Assets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assets__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Assets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Organization ID is the Coinbase Cloud ID assigned to each customer. Org ID can be found in the Coinbase Cloud Console.</inlineHelpText>
    <label>Organization ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/base/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>[SFCC-396] Account Region based on Countries of Incorporation</description>
    <inlineHelpText>Region is based on Countries of Incorporation. If multiple countries from different Regions are selected, then Region is Global.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/base/globalValueSets/Country_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <masterLabel>Country Codes</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Customer_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Customer Tier</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <description>[SFCC-396] Region picklist for Lead, Account and Opportunity</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/base/classes/AccountsSelectorCBD.cls
public inherited sharing class AccountsSelectorCBD extends ApplicationSObjectSelector implements IAccountsSelector {
    public static IAccountsSelector newInstance() {
        return (IAccountsSelector) Application.Selector.newInstance(Account.SObjectType);
    }

    public Schema.sObjectType getSObjectType() {
        return Account.SObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Account.Id,
            Account.Name,
            Account.RecordTypeId,
            Account.Customer_Tier__c,
            Account.Country_Codes__c,
            Account.Number_Of_Assets__c,
            Account.Billing_Contact__c,
            Account.Region__c,
            Account.CS_Account_Status__c,
            Account.Organization_ID__c,
            Account.CS_Owner__c
        };
    }

    @TestVisible
    private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
        return new List<Schema.SObjectField>{};
    }

    public List<Account> selectById(Set<Id> idSet) {
        return (List<Account>) selectSObjectsById(idSet == null ? new Set<Id>() : idSet);
    }

    public List<Account> selectByIdWithLimit(Set<Id> idSet, Integer queryLimit) {
        fflib_QueryFactory queryFactory = newQueryFactory()
            .setCondition('Id IN: idSet')
            .setLimit(queryLimit);
        return (List<Account>) Database.query(queryFactory.toSOQL());
    }

    public List<Account> selectByRecordTypeId(Set<Id> recordTypeIds) {
        fflib_QueryFactory queryFactory = newQueryFactory()
            .setCondition('RecordTypeId IN: recordTypeIds');
        return (List<Account>) Database.query(queryFactory.toSOQL());
    }

    public List<Account> selectByIdWithAssets(Set<Id> idSet, Set<String> assetFields) {
        fflib_QueryFactory queryFactory = newQueryFactory().setCondition('Id IN: idSet');
        queryFactory.subSelectQuery('Assets').selectFields(assetFields);
        return (List<Account>) Database.query(queryFactory.toSOQL());
    }

    public List<Account> selectByIdWithAccountContactRelations(
        Set<Id> idSet,
        Set<String> accountContactFields
    ) {
        fflib_QueryFactory queryFactory = newQueryFactory().setCondition('Id IN: idSet');
        queryFactory.subSelectQuery('AccountContactRelations').selectFields(accountContactFields);
        return (List<Account>) Database.query(queryFactory.toSOQL());
    }

    public String testing() {
        Set<String> assetFields = new Set<String>{ 'Id', 'Name' };
        Set<String> accountFields = new Set<String>{ 'CreatedById' };
        fflib_QueryFactory queryFactory = newQueryFactory()
            .setCondition('Id IN: idSet')
            .selectFields(accountFields);
        queryFactory.subSelectQuery('Assets').selectFields(assetFields);
        return queryFactory.toSOQL();
    }
}