src/base/objects/Account/fields/Coinbase_Wallet_Connection_Date__c.field-meta.xml
<CustomField>
    <fullName>Coinbase_Wallet_Connection_Date__c</fullName>
    <description>SFCC-859</description>
    <inlineHelpText>When was Coinbase Wallet added to this Partner&apos;s platform?</inlineHelpText>
    <label>Coinbase Wallet Connection Date</label>
    <type>Date</type>
</CustomField>

src/base/objects/Account/fields/Countries_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Countries_of_Incorporation__c</fullName>
    <label>Countries of Incorporation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_of_Incorporation</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Country_Codes__c</fullName>
    <label>Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Codes</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>[SFCC-396] Account Region based on Countries of Incorporation</description>
    <inlineHelpText>Region is based on Countries of Incorporation. If multiple countries from different Regions are selected, then Region is Global.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/recordTypes/Business_Development_Partnerships.recordType-meta.xml
<RecordType>
    <fullName>Business_Development_Partnerships</fullName>
    <active>true</active>
    <description>Business Development &amp; Partnerships Accounts</description>
    <label>Business Development &amp; Partnerships</label>
</RecordType>

src/base/objects/Account/recordTypes/Cloud_Account.recordType-meta.xml
<RecordType>
    <fullName>Cloud_Account</fullName>
    <active>true</active>
    <label>Cloud Account</label>
</RecordType>

src/base/globalValueSets/Countries_of_Incorporation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries of Incorporation</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/globalValueSets/Country_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>JP</fullName>
    </customValue>
    <masterLabel>Country Codes</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Customer_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Customer Tier</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <description>[SFCC-396] Region picklist for Lead, Account and Opportunity</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/base/classes/AccountCBDIntegrationTest.cls
@isTest
public with sharing class AccountCBDIntegrationTest {
    private static final String EST_Timezone = 'EST - Eastern Standard Time - GMT-5:00';

    private static final Id BD_ACCOUNT_RECORDTYPE_ID = SObjectType.Account
        .getRecordTypeInfosByDeveloperName()
        .get('Business_Development_Partnerships')
        .getRecordTypeId();

    private static final Id CLOUD_ACCOUNT_RECORDTYPE_ID = SObjectType.Account
        .getRecordTypeInfosByDeveloperName()
        .get('Cloud_Account')
        .getRecordTypeId();

    @isTest
    public static void testCountryCodes() {
        Account accountRecord = buildAccount('New Account Integration', '3');
        accountRecord.Countries_of_Incorporation__c = 'Japan;Germany';
        accountRecord.RecordTypeId = CLOUD_ACCOUNT_RECORDTYPE_ID;
        accountRecord.Ideal_Timezone__c = EST_Timezone;

        Test.startTest();
        insert accountRecord;
        Test.stopTest();

        Account updatedAccount = [
            SELECT Country_Codes__c, Region__c
            FROM Account
            WHERE Id = :accountRecord.Id
        ];
        system.assert(
            updatedAccount.Country_Codes__c.contains('DE'),
            'Country Code not set as expected'
        );

        system.assert(
            updatedAccount.Country_Codes__c.contains('JP'),
            'Country Code not set as expected'
        );
        system.assertEquals('Global', updatedAccount.Region__c, 'Region not set as expected');
    }

    @isTest
    public static void testTaskCreation() {
        Account accountRecord = buildAccount('New Account Integration Tasking', '3');
        accountRecord.RecordTypeId = BD_ACCOUNT_RECORDTYPE_ID;
        accountRecord.Ideal_Timezone__c = EST_Timezone;
        accountRecord.Coinbase_Wallet_Connection_Date__c = Date.today().addDays(3);
        insert accountRecord;

        List<Task> taskList = [SELECT Status, Priority FROM Task WHERE WhatId = :accountRecord.Id];
        system.assertEquals(1, taskList.size(), 'Incorrect number of tasks created');
        system.assertEquals(taskList[0].Status, 'Open', 'Task created in incorrect status');
        system.assertEquals(taskList[0].Priority, 'Normal', 'Task priority is incorrect');
    }

    private static Account buildAccount(String accountName, String customerTier) {
        Account accountRecord = new Account(Name = accountName, Customer_Tier__c = customerTier);
        return accountRecord;
    }
}