src/base/objects/Account/fields/Competitors__c.field-meta.xml
<CustomField>
    <fullName>Competitors__c</fullName>
    <description>[SFCC-859] Wallet Information field</description>
    <label>Competitors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Dapp_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Dapp_Sub_Type__c</fullName>
    <description>SFCC-986</description>
    <label>Dapp Sub-Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>DEFI</fullName>
            </value>
            <value>
                <fullName>DEX</fullName>
            </value>
            <value>
                <fullName>Collectibles</fullName>
            </value>
            <value>
                <fullName>NFT Marketplace</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Competitors__c.field-meta.xml
<CustomField>
    <fullName>Competitors__c</fullName>
    <description>[SFCC-671] Opportunity Wallet Record Type Field</description>
    <label>Wallet Competitors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Dapp_Url__c.field-meta.xml
<CustomField>
    <fullName>Dapp_Url__c</fullName>
    <label>Dapp Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/base/objects/Opportunity/fields/Internal_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Review_Status__c</fullName>
    <label>Internal Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Wallet_Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Campaign_Type__c</fullName>
    <label>Wallet Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incentive</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Wallet Quest</fullName>
            </value>
            <value>
                <fullName>Co-Marketing</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Wallet_OKR_Cohort__c.field-meta.xml
<CustomField>
    <fullName>Wallet_OKR_Cohort__c</fullName>
    <label>Wallet OKR Cohort</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/base/objects/Opportunity/fields/Wallet_Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Opportunity_Type__c</fullName>
    <label>Wallet Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coinbase Wallet Integration</fullName>
            </value>
            <value>
                <fullName>Wallet Campaign/Quest</fullName>
            </value>
            <value>
                <fullName>Dapp Discovery Browsers</fullName>
            </value>
            <value>
                <fullName>Dapp Marketplace Integration</fullName>
                <isActive>false</isActive>
                <label>Dapp Marketplace Integration</label>
            </value>
            <value>
                <fullName>DmP Qualification</fullName>
                <isActive>false</isActive>
                <label>DmP Qualification</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/globalValueSets/Competitors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Metamask</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet Connect</fullName>
    </customValue>
    <customValue>
        <fullName>Trust Wallet</fullName>
    </customValue>
    <customValue>
        <fullName>Rainbow</fullName>
    </customValue>
    <customValue>
        <fullName>Phantom</fullName>
    </customValue>
    <description>SFCC-859</description>
    <masterLabel>Competitors</masterLabel>
</GlobalValueSet>

src/base/classes/TA_Opportunity_OpportunityValidatorTest.cls
/**
 * @description       : Test class for TA_Opportunity_OpportunityValidator
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 01-03-2023
 * @last modified by  : Lavanya Tangati
**/
@isTest
private class TA_Opportunity_OpportunityValidatorTest {
    @isTest
    static void validateOppFilesValidationNegative(){

        List<Account> a = TestDataHelper.getAccounts(1, true);
        List<Opportunity> opp = TestDataHelper.getOpportunities(a[0].Id, 1, false);
        opp[0].RecordTypeId =  TA_Opportunity_OpportunityValidator.WALLET_OPPORTUNITY_RECORDTYPE_ID;
        insert opp;

        opp[0].Wallet_Opportunity_Type__c = 'Wallet Campaign/Quest';
        opp[0].StageName = 'Executed';

        try{
            update opp[0];
            System.assert(false, 'An error should have thrown on moving the Stage to Executed and beyond');
        }
        catch(Exception ex){
            System.assert(true, ex.getMessage());
        }
    }

    @isTest
    static void validateOppFilesValidationPositive(){

        List<Account> a = TestDataHelper.getAccounts(1, true);
        List<Opportunity> opp = TestDataHelper.getOpportunities(a[0].Id, 1, false);
        opp[0].RecordTypeId =  TA_Opportunity_OpportunityValidator.WALLET_OPPORTUNITY_RECORDTYPE_ID;
        insert opp;

        ContentVersion contentVersion = new ContentVersion(
            Title = 'order form',
            PathOnClient = 'order_form.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );

        insert contentVersion;    
        List<ContentDocument> documents = [
        SELECT Id, Title, LatestPublishedVersionId 
        FROM ContentDocument
        ];

        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = opp[0].id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;

        opp[0].Wallet_Opportunity_Type__c = 'Wallet Campaign/Quest';
        opp[0].StageName = 'Executed';
        opp[0].Internal_Review_Status__c = 'Approved';
        opp[0].Wallet_Campaign_Type__c = 'Incentive';

        try{
            update opp[0];
            System.assert(true, 'An error should not have thrown as there is afile attached to the Opportunity');
        }
        catch(Exception ex){
            System.assert(false, ex.getMessage());
        }
    }

    @isTest
    static void validateOppFilesWalletTypeCheck(){

        List<Account> a = TestDataHelper.getAccounts(1, false);
        a[0].Dapp_Sub_Type__c = 'Gaming';
        insert a;

        List<Opportunity> opp = TestDataHelper.getOpportunities(a[0].Id, 1, false);
        opp[0].RecordTypeId =  TA_Opportunity_OpportunityValidator.WALLET_OPPORTUNITY_RECORDTYPE_ID;
        insert opp;

        opp[0].Wallet_Opportunity_Type__c = 'Coinbase Wallet Integration';
        opp[0].Dapp_Url__c ='test.com';
        opp[0].Competitors__c ='Metamask';
        opp[0].Wallet_OKR_Cohort__c ='test123';
        opp[0].StageName = 'Executed';

        try{
            update opp[0];
            System.assert(true, 'An error should not have thrown as there is afile attached to the Opportunity');
        }
        catch(Exception ex){
            System.assert(false, ex.getMessage());
        }
    }
}