src/base/objects/Account/fields/Countries_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Countries_of_Incorporation__c</fullName>
    <label>Countries of Incorporation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_of_Incorporation</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Country_Codes__c</fullName>
    <label>Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Codes</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Segment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>[SFCC-396] Account Region based on Countries of Incorporation</description>
    <inlineHelpText>Region is based on Countries of Incorporation. If multiple countries from different Regions are selected, then Region is Global.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Countries_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Countries_of_Incorporation__c</fullName>
    <inlineHelpText>Upon creation, Countries of Incorporation is defaulted from Account</inlineHelpText>
    <label>Countries of Incorporation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_of_Incorporation</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <inlineHelpText>Upon creation, Customer Segment is defaulted from Account</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Segment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Customer_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Subsegment__c</fullName>
    <inlineHelpText>Upon creation, Customer Subsegment is defaulted from Account</inlineHelpText>
    <label>Customer Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Customer_Subsegment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>[SFCC-396] Opportunity Region based on Countries of Incorporation</description>
    <inlineHelpText>Region is based on Countries of Incorporation. If multiple countries from different Regions are selected, then Region is Global.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/base/globalValueSets/Countries_of_Incorporation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries of Incorporation</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/globalValueSets/Country_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <masterLabel>Country Codes</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Customer_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Coinbase Team</fullName>
    </customValue>
    <customValue>
        <fullName>Startup</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Service - Traditional</fullName>
        <isActive>false</isActive>
        <label>Financial Service - Traditional</label>
    </customValue>
    <customValue>
        <fullName>Financial Service - Crypto Native</fullName>
        <isActive>false</isActive>
        <label>Financial Service - Crypto Native</label>
    </customValue>
    <customValue>
        <fullName>Startups</fullName>
        <isActive>false</isActive>
        <label>Startups</label>
    </customValue>
    <masterLabel>Customer Segment</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Customer_Subsegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Developers</fullName>
    </customValue>
    <customValue>
        <fullName>Protocol Foundation</fullName>
    </customValue>
    <customValue>
        <fullName>Wallets</fullName>
    </customValue>
    <customValue>
        <fullName>DeFi</fullName>
    </customValue>
    <customValue>
        <fullName>NFTs / Collectibles</fullName>
    </customValue>
    <customValue>
        <fullName>GameFi</fullName>
    </customValue>
    <customValue>
        <fullName>On-Chain Data</fullName>
    </customValue>
    <customValue>
        <fullName>Other Crypto / Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Web 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Traditional Brokers</fullName>
    </customValue>
    <customValue>
        <fullName>Traditional Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Ecommerce/Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Providers</fullName>
    </customValue>
    <customValue>
        <fullName>NPO / NGO</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto Asset Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto Hedge Funds</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto Venture Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto HNWI</fullName>
    </customValue>
    <customValue>
        <fullName>ETF/ETP</fullName>
    </customValue>
    <customValue>
        <fullName>Allocators</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional Private Wealth</fullName>
    </customValue>
    <customValue>
        <fullName>Traditional Asset Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Traditional Hedge Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Traditional VC / PE</fullName>
    </customValue>
    <masterLabel>Customer Subsegment</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <description>[SFCC-396] Region picklist for Lead, Account and Opportunity</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/base/classes/TA_Opportunity_HandleCountryCodeRegion.cls
/**
 * @description       : Handle CountryCode And Region updates
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 12-09-2022
 * @last modified by  : Lavanya Tangati
**/
public without sharing class TA_Opportunity_HandleCountryCodeRegion implements TriggerAction.BeforeInsert, TriggerAction.BeforeUpdate {
    
    private static Set<Id> accountIds = new Set<Id>();
    List<Opportunity> qualifiedOpps =  new List<Opportunity>();

    public void BeforeInsert(List<Opportunity> newList) {
        //qualify
        for (Opportunity opp : newList) {
            accountIds.add(opp.AccountId);
        }

        if(!accountIds.isEmpty()){
            updateFieldsFromAccount(newList);
        }

        //first fields on Opp needs to be set from Account from the above method, then only we can set Country Codes and Region
        for (Opportunity opp : newList) {
            if (String.isNotEmpty(opp.Countries_of_Incorporation__c)) {
                CountryCodeCalculator.setCountryCodesAndRegion(opp);
            }
        }

    }

    public void BeforeUpdate(List<Opportunity> newList, List<Opportunity> oldList) {
        Map<Id, Opportunity>  oldMap = new Map<Id, Opportunity>(oldList);
        
        //qualify
        for (Opportunity opp : newList) {
            Opportunity oldOpp = oldMap.get(opp.Id);
            accountIds.add(opp.AccountId);
            if(opp.Countries_of_Incorporation__c != oldOpp.Countries_of_Incorporation__c){
                qualifiedOpps.add(opp);
            }
        }

        //Set CountryCode and Region
        for (Opportunity opp : qualifiedOpps) {
            Account accountRecord = accountMap?.get(opp.AccountId);
            if (String.isEmpty(opp.Countries_of_Incorporation__c)) {
                opp.Country_Codes__c = null;
                opp.Region__c = null;
            } 
            else {
                validateOppCountryIncorporation(opp, accountRecord);
                CountryCodeCalculator.setCountryCodesAndRegion(opp);
            }
        }
    }

    private static void validateOppCountryIncorporation(Opportunity oppRecord, Account accountRecord) {
        Set<String> oppCountries = OrgUtil.createSetFromPicklistField( oppRecord?.Countries_of_Incorporation__c);
        Set<String> accountCountries = OrgUtil.createSetFromPicklistField( accountRecord?.Countries_of_Incorporation__c);
        for (String oppCountry : oppCountries) {
            if (!accountCountries.contains(oppCountry)) {
                oppRecord.addError(
					'Cannot add ' + oppCountry + ' as a Country of Incorporation. ' + 
					'You must first add ' + oppCountry + ' to the Countries of Incorporation of this Opportunity\'s Account record '
                );
            }
        }
    }

    public static void updateFieldsFromAccount(List<Opportunity> newList) {
        for (Opportunity opp : newList) {
            Account account = accountMap.get(opp.AccountId);
            opp.Countries_of_Incorporation__c = account.Countries_of_Incorporation__c;
            opp.Customer_Segment__c = account.Customer_Segment__c;
            opp.Customer_Subsegment__c = account.Customer_Subsegment__c;
        }
    }

    private static Map<Id,Account> accountMap{
        get{
            if(accountMap == null){
                accountMap =  new Map<Id, Account>( [
                    SELECT Id, Countries_of_Incorporation__c, Customer_Segment__c, Customer_Subsegment__c
                    FROM Account
                    WHERE Id IN :accountIds
                ]);
            }
            return accountMap;
        }
        private set;
    }

}