src/base/objects/Account/fields/Countries_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Countries_of_Incorporation__c</fullName>
    <label>Countries of Incorporation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_of_Incorporation</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Country_Codes__c</fullName>
    <label>Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Codes</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>[SFCC-396] Account Region based on Countries of Incorporation</description>
    <inlineHelpText>Region is based on Countries of Incorporation. If multiple countries from different Regions are selected, then Region is Global.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/base/globalValueSets/Countries_of_Incorporation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries of Incorporation</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/globalValueSets/Country_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>CN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>JP</fullName>
    </customValue>
    <masterLabel>Country Codes</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Customer_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Customer Tier</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <description>[SFCC-396] Region picklist for Lead, Account and Opportunity</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/base/classes/TA_Account_HandleCountryAndRegionTest.cls
/**
 * @description       : 
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 01-05-2023
 * @last modified by  : Lavanya Tangati
**/
//Note: This test class takes advantage of the fact that Lists and SObjects are passed by reference,
//so changes to these objects within a trigger class can be read and detected outside the trigger classes in this
//test class
@isTest
private class TA_Account_HandleCountryAndRegionTest {
    @isTest
    public static void testAccountNoCountries() {
        Account mockAccount = buildMockAccount('Incorp Testing', '');
        List<Account> accountList = new List<Account>{ mockAccount };

        TA_Account_HandleCountryCodeAndRegion triggerObject = new TA_Account_HandleCountryCodeAndRegion();
        triggerObject.BeforeInsert(accountList);

        Account modifiedAccount = accountList[0];
        system.assertEquals(null, modifiedAccount.Region__c, 'Region should be null');
    }

    @isTest
    public static void testAccountWithOneRegion() {
        Account mockAccount = buildMockAccount('Incorp Testing', 'Japan;China');
        List<Account> accountList = new List<Account>{ mockAccount };

        TA_Account_HandleCountryCodeAndRegion triggerObject = new TA_Account_HandleCountryCodeAndRegion();
        triggerObject.BeforeInsert(accountList);

        Account modifiedAccount = accountList[0];
        system.assertEquals('APAC', modifiedAccount.Region__c, 'Region not set as expected');
        system.assert(
            modifiedAccount.Country_Codes__c.contains('JP'),
            'Country Code not set as expected'
        );
        system.assert(
            modifiedAccount.Country_Codes__c.contains('CN'),
            'Country Code not set as expected'
        );
    }

    @isTest
    public static void testAccountWithTwoRegions() {
        Account mockAccount = buildMockAccount('Incorp Testing', 'Japan;Germany');
        List<Account> accountList = new List<Account>{ mockAccount };

        TA_Account_HandleCountryCodeAndRegion triggerObject = new TA_Account_HandleCountryCodeAndRegion();
        triggerObject.BeforeInsert(accountList);

        Account modifiedAccount = accountList[0];
        system.assertEquals('Global', modifiedAccount.Region__c, 'Region not set as expected');
        system.assert(
            modifiedAccount.Country_Codes__c.contains('JP'),
            'Country Code not set as expected'
        );
        system.assert(
            modifiedAccount.Country_Codes__c.contains('DE'),
            'Country Code not set as expected'
        );
    }

    @isTest
    public static void testAccountWithOneRegionOnUpdate() {
        Account mockAccountOld = buildMockAccount('Incorp Testing', 'Japan;China');
        List<Account> accountListOld = new List<Account>{ mockAccountOld };

        Account mockAccountNew = mockAccountOld.clone(true);
        mockAccountNew.Countries_of_Incorporation__c = 'Japan;China;Canada';
        List<Account> accountListNew = new List<Account>{ mockAccountNew };

        TA_Account_HandleCountryCodeAndRegion triggerObject = new TA_Account_HandleCountryCodeAndRegion();
        triggerObject.BeforeUpdate(accountListNew, accountListOld);

        Account modifiedAccount = accountListNew[0];
        system.assertEquals('Global', modifiedAccount.Region__c, 'Region not set as expected');
        system.assert(
            modifiedAccount.Country_Codes__c.contains('JP'),
            'Country Code not set as expected'
        );
        system.assert(
            modifiedAccount.Country_Codes__c.contains('CN'),
            'Country Code not set as expected'
        );
    }

    @isTest
    public static void testTwoAccounts() {
        Account mockAccountApac = buildMockAccount('Incorp Testing', 'Japan;China');
        Account mockAccountGlobal = buildMockAccount('Incorp Testing', 'Japan;Canada;Ireland');
        List<Account> accountList = new List<Account>{ mockAccountApac, mockAccountGlobal };

        TA_Account_HandleCountryCodeAndRegion triggerObject = new TA_Account_HandleCountryCodeAndRegion();
        triggerObject.BeforeInsert(accountList);

        Account modifiedAccountApac = accountList[0];
        system.assertEquals('APAC', modifiedAccountApac.Region__c, 'Region not set as expected');
        system.assert(
            modifiedAccountApac.Country_Codes__c.contains('JP'),
            'Country Code not set as expected'
        );
        system.assert(
            modifiedAccountApac.Country_Codes__c.contains('CN'),
            'Country Code not set as expected'
        );

        Account modifiedAccountGlobal = accountList[1];
        system.assertEquals(
            'Global',
            modifiedAccountGlobal.Region__c,
            'Region not set as expected'
        );
        system.assert(
            modifiedAccountGlobal.Country_Codes__c.contains('JP'),
            'Country Code not set as expected'
        );
        system.assert(
            modifiedAccountGlobal.Country_Codes__c.contains('IE'),
            'Country Code not set as expected'
        );
        system.assert(
            modifiedAccountGlobal.Country_Codes__c.contains('CA'),
            'Country Code not set as expected'
        );
    }

    private static Account buildMockAccount(String accountName, String countryString) {
        Account mockAccount = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Name = accountName,
            Customer_Tier__c = '3',
            Countries_of_Incorporation__c = countryString
        );

        return mockAccount;
    }
}