src/base/objects/Account/fields/CS_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>CS_Account_Status__c</fullName>
    <description>SFCC-790 - This picklist value displays if an Account is Active, Inactive, Churned or Not Onboarded</description>
    <label>CS Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Churned</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Not Onboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Number_of_Assets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assets__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Assets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Account/recordTypes/Cloud_Account.recordType-meta.xml
<RecordType>
    <fullName>Cloud_Account</fullName>
    <active>true</active>
    <label>Cloud Account</label>
</RecordType>

src/base/objects/Asset/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The type of product for this asset.</description>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>The protocol associated with this asset.</description>
    <label>Protocol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Protocol_List</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/globalValueSets/Customer_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Customer Tier</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Protocol_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acala</fullName>
    </customValue>
    <customValue>
        <fullName>Algorand</fullName>
    </customValue>
    <customValue>
        <fullName>Aptos</fullName>
    </customValue>
    <customValue>
        <fullName>Avalanche</fullName>
    </customValue>
    <customValue>
        <fullName>Axelar</fullName>
    </customValue>
    <customValue>
        <fullName>Binance Smart Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin SV</fullName>
    </customValue>
    <customValue>
        <fullName>Cardano</fullName>
    </customValue>
    <customValue>
        <fullName>Celo</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmos</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto.com</fullName>
    </customValue>
    <customValue>
        <fullName>Decred</fullName>
    </customValue>
    <customValue>
        <fullName>Diem</fullName>
    </customValue>
    <customValue>
        <fullName>Dogecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Edgeware</fullName>
    </customValue>
    <customValue>
        <fullName>EOS</fullName>
    </customValue>
    <customValue>
        <fullName>Eth2</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum 1.X</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Evmos</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Helium</fullName>
    </customValue>
    <customValue>
        <fullName>Karura</fullName>
    </customValue>
    <customValue>
        <fullName>Keep</fullName>
    </customValue>
    <customValue>
        <fullName>Kusama</fullName>
    </customValue>
    <customValue>
        <fullName>Litecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Livepeer</fullName>
    </customValue>
    <masterLabel>Protocol List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/classes/AssetCBDIntegrationTest.cls
@isTest
public with sharing class AssetCBDIntegrationTest {
    private static final String EST_Timezone = 'EST - Eastern Standard Time - GMT-5:00';

    private static final Id CLOUD_ACCOUNT_RECORDTYPE_ID = SObjectType.Account
        .getRecordTypeInfosByDeveloperName()
        .get('Cloud_Account')
        .getRecordTypeId();

    @TestSetup
    public static void createTestData() {
        List<Account> accountsToCreate = new List<Account>();
        for (Integer i = 1; i <= 1; i++) {
            Account accountRecord = buildAccount('Asset testing Account ' + String.valueOf(i));
            accountsToCreate.add(accountRecord);
        }
        insert accountsToCreate;
    }

    @isTest
    public static void createAssetsOnAccount() {
        List<Asset> assetsToCreate = new List<Asset>();
        Account accountToLink = [SELECT Id FROM Account LIMIT 1];
        Integer numberOfAssetsToCreate = 2;

        for (Integer i = 1; i <= numberOfAssetsToCreate; i++) {
            assetsToCreate.add(buildAsset('Churned', 'Bitcoin', 0, accountToLink.Id, i));
        }

        Test.startTest();
        insert assetsToCreate;
        Test.stopTest();

        Account updatedAccount = [
            SELECT Number_Of_Assets__c
            FROM Account
            WHERE Id = :accountToLink.Id
        ];
        system.assertEquals(
            numberOfAssetsToCreate,
            updatedAccount.Number_Of_Assets__c,
            'Number of assets not updated on Account'
        );
    }

    @isTest
    public static void testAccountStatusUpdate() {
        List<Asset> assetsToCreate = new List<Asset>();
        Account accountToLink = [SELECT Id FROM Account LIMIT 1];
        Integer numberOfAssetsToCreate = 1;

        for (Integer i = 1; i <= numberOfAssetsToCreate; i++) {
            assetsToCreate.add(buildAsset('Churned', 'Bitcoin', 0, accountToLink.Id, i));
        }

        Test.startTest();
        insert assetsToCreate;
        Test.stopTest();

        Account updatedAccount = [
            SELECT CS_Account_Status__c, Number_Of_Assets__c
            FROM Account
            WHERE Id = :accountToLink.Id
        ];
        system.assertEquals(
            'Churned',
            updatedAccount.CS_Account_Status__c,
            'Account status not set correctly'
        );
    }

    private static Asset buildAsset(
        String status,
        String protocol,
        Decimal quantity,
        Id accountId,
        Integer counter
    ) {
        Asset assetRecord = new Asset();
        assetRecord.Name = 'Asset record for ' + String.valueOf(counter) + protocol;
        assetRecord.AccountId = accountId;
        assetRecord.Quantity = quantity;
        assetRecord.Status = status;
        assetRecord.Protocol__c = protocol;
        assetRecord.Product_Type__c = 'Delegation';
        return assetRecord;
    }

    private static Account buildAccount(String accountName) {
        Account accountRecord = new Account(Name = accountName);
        accountRecord.Customer_Tier__c = '3';
        accountRecord.RecordTypeId = CLOUD_ACCOUNT_RECORDTYPE_ID;
        accountRecord.Ideal_Timezone__c = EST_Timezone;
        return accountRecord;
    }
}