src/base/objects/Account/fields/CS_Owner__c.field-meta.xml
<CustomField>
    <fullName>CS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This account&apos;s CS owner</description>
    <inlineHelpText>Engagement Manager</inlineHelpText>
    <label>EM Primary Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Number_of_Assets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assets__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Assets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/base/objects/Asset/fields/Bill__c.field-meta.xml
<CustomField>
    <fullName>Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill</label>
    <referenceTo>Bill__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Asset/fields/CS_Owner__c.field-meta.xml
<CustomField>
    <fullName>CS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AssetsCSOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to represent the bills associated with each of our accounts.</description>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/globalValueSets/Customer_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Customer Tier</masterLabel>
</GlobalValueSet>

src/base/classes/TA_Asset_UpdateAssetsOnAccountTest.cls
/**
 * @description       : 
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 01-05-2023
 * @last modified by  : Lavanya Tangati
**/
@isTest
public with sharing class TA_Asset_UpdateAssetsOnAccountTest {
    @isTest
    public static void testAssetWithAccount() {
        Id csOwnerId = fflib_IDGenerator.generate(User.SObjectType);
        Account mockAccount = buildMockAccount('New Automate CSA Test', csOwnerId, 0);
        Asset mockAsset = buildMockAsset('Asset Active', 'Active', 15, mockAccount.Id);

        Account accountWithRelation = linkAssetsToAccount(
            mockAccount,
            new List<Asset>{ mockAsset }
        );
        Set<Id> accIds = new Set<Id>{ accountWithRelation.Id };
        setAccountMockSelector(accIds, new List<Account>{ accountWithRelation });
        Test.startTest();
        TA_Asset_UpdateAssetsOnAccount triggerObject = new TA_Asset_UpdateAssetsOnAccount();
        List<Account> newAccounts = triggerObject.buildAccountsForUpdate(
            new List<Asset>{ mockAsset },
            null
        );
        Test.stopTest();
        system.assertEquals(
            1,
            newAccounts[0].Number_Of_Assets__c,
            'Number of Assets on Account not set as expected'
        );
    }

    @isTest
    public static void testAssetUpdate() {
        Id csOwnerId = fflib_IDGenerator.generate(User.SObjectType);
        Account mockAccount = buildMockAccount('New Automate CSA Test', csOwnerId, 1);
        Asset mockAsset = buildMockAsset('Asset Active', 'Active', 15, mockAccount.Id);
        Asset updatedAsset = mockAsset.clone(true);

        Account accountWithRelation = linkAssetsToAccount(
            mockAccount,
            new List<Asset>{ mockAsset }
        );
        Set<Id> accIds = new Set<Id>{ accountWithRelation.Id };
        setAccountMockSelector(accIds, new List<Account>{ accountWithRelation });
        Test.startTest();
        TA_Asset_UpdateAssetsOnAccount triggerObject = new TA_Asset_UpdateAssetsOnAccount();
        List<Account> newAccounts = triggerObject.updateAssetNumberOnAccount(
            new List<Asset>{ mockAsset },
            new List<Asset>{ updatedAsset }
        );
        Test.stopTest();
        system.assertEquals(
            0,
            newAccounts.size(),
            'Non-relevant Asset update triggered an Account update'
        );
    }
    private static Account buildMockAccount(
        String accountName,
        Id csOwnerId,
        Decimal numberOfAssets
    ) {
        Account mockAccount = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Name = accountName,
            Customer_Tier__c = '3',
            Number_Of_Assets__c = numberOfAssets
        );

        if (csOwnerId != null) {
            mockAccount.CS_Owner__c = csOwnerId;
        }
        return mockAccount;
    }

    private static Asset buildMockAsset(
        String assetName,
        String assetStatus,
        Integer assetQuantity,
        Id accountId
    ) {
        Asset mockAsset = new Asset(
            Id = fflib_IDGenerator.generate(Asset.SObjectType),
            Name = assetName,
            Status = assetStatus,
            Quantity = assetQuantity,
            Bill__c = fflib_IDGenerator.generate(Bill__c.SObjectType)
        );

        if (accountId != null) {
            mockAsset.AccountId = accountId;
        }

        return mockAsset;
    }

    private static Account linkAssetsToAccount(Account mockAccount, List<Asset> assetList) {
        List<Account> mockedRelationList = (List<Account>) fflib_ApexMocksUtils.makeRelationship(
            List<Account>.class,
            new List<Account>{ mockAccount },
            Asset.AccountId,
            new List<List<Asset>>{ assetList }
        );

        return mockedRelationList[0];
    }

    private static void setAccountMockSelector(Set<Id> idsToQuery, List<Account> listToReturn) {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IAccountsSelector mockSelector = (IAccountsSelector) mocks.mock(IAccountsSelector.class);
        // Start stubbing
        mocks.startStubbing();
        Set<String> assetFieldsToQuery = new Set<String>{ 'Id', 'Name' };
        mocks.when(mockSelector.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(mockSelector.selectByIdWithAssets(idsToQuery, assetFieldsToQuery))
            .thenReturn(listToReturn);
        mocks.stopStubbing();

        //Inject Mock
        Application.Selector.setMock(mockSelector);
    }
}