src/base/objects/Account/fields/CS_Owner__c.field-meta.xml
<CustomField>
    <fullName>CS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This account&apos;s CS owner</description>
    <inlineHelpText>Engagement Manager</inlineHelpText>
    <label>EM Primary Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Asset/fields/Bill__c.field-meta.xml
<CustomField>
    <fullName>Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill</label>
    <referenceTo>Bill__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Asset/fields/CS_Owner__c.field-meta.xml
<CustomField>
    <fullName>CS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AssetsCSOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to represent the bills associated with each of our accounts.</description>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/classes/AssetsSelectorCBD.cls
public inherited sharing class AssetsSelectorCBD extends ApplicationSObjectSelector implements IAssetsSelector {
    public static IAssetsSelector newInstance() {
        return (IAssetsSelector) Application.Selector.newInstance(Asset.SObjectType);
    }

    public Schema.sObjectType getSObjectType() {
        return Asset.SObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Asset.Id,
            Asset.Name,
            Asset.Status,
            Asset.Quantity,
            Asset.Bill__c,
            Asset.CS_Owner__c
        };
    }

    @TestVisible
    private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
        return new List<Schema.SObjectField>{};
    }

    public List<Asset> selectById(Set<Id> idSet) {
        return (List<Asset>) selectSObjectsById(idSet == null ? new Set<Id>() : idSet);
    }

    public List<Account> selectByAccountIds(Set<Id> accountIds) {
        fflib_QueryFactory queryFactory = newQueryFactory()
            .setCondition('AccountId IN: accountIds ');
        return (List<Account>) Database.query(queryFactory.toSOQL());
    }
}