src/base/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Segment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The valuation of the company.</description>
    <inlineHelpText>The valuation of the company. This is a fairly loose metric, as a lot of these values are not public information, but use your best judgement.</inlineHelpText>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small Cap (&lt; $150M)</fullName>
                <default>true</default>
                <label>Small Cap (&lt; $150M)</label>
            </value>
            <value>
                <fullName>Mid Cap ($150M &lt; $1B)</fullName>
            </value>
            <value>
                <fullName>Large Cap (&gt; $1B)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Bill__c.field-meta.xml
<CustomField>
    <fullName>Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill</label>
    <referenceTo>Bill__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Asset/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The type of product for this asset.</description>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>The protocol associated with this asset.</description>
    <label>Protocol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Protocol_List</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to represent the bills associated with each of our accounts.</description>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/base/objects/Bill__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This is the Account to which this Bill belongs.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bills</relationshipLabel>
    <relationshipName>Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/base/objects/Bill__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <description>The frequency at which this bill comes due.</description>
    <inlineHelpText>If the billing frequency is non-standard, be sure to make note of the details in the Special Terms field.</inlineHelpText>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Non-Standard (Make Note)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Segment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Tier</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Lead/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Delegations</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
                <isActive>false</isActive>
                <label>Node</label>
            </value>
            <value>
                <fullName>Query &amp; Transact</fullName>
                <isActive>false</isActive>
                <label>Query &amp; Transact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Lead/recordTypes/Standard_Lead.recordType-meta.xml
<RecordType>
    <fullName>Standard_Lead</fullName>
    <active>true</active>
    <businessProcess>Standard Lead Process</businessProcess>
    <label>Standard Lead</label>
</RecordType>

src/base/objects/Opportunity/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <inlineHelpText>Upon creation, Customer Segment is defaulted from Account</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Segment</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <description>The ideal timezone of this opportunity for onboardings, communication, etc.</description>
    <inlineHelpText>The ideal timezone of this opportunity for onboardings, communication, etc. Required to move a deal to Trial or Closed Won.</inlineHelpText>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Onboarding_Required__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Required__c</fullName>
    <description>OPS-5156</description>
    <inlineHelpText>Please denote whether this customer requires an Onboarding or New Asset Case created. This field is required when the Opportunity is Closed Won.</inlineHelpText>
    <label>Onboarding Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>New Customer - Onboard</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Onboard</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
                <isActive>false</isActive>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Other_Amount__c.field-meta.xml
<CustomField>
    <fullName>Other_Amount__c</fullName>
    <label>Other Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact associate with this opportunity.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
                <isActive>false</isActive>
                <label>Node</label>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/recordTypes/Algorand_Pipeline.recordType-meta.xml
<RecordType>
    <fullName>Algorand_Pipeline</fullName>
    <active>true</active>
    <businessProcess>Participation Sales Process</businessProcess>
    <description>Algorand Sales Pipeline</description>
    <label>Algorand Pipeline</label>
</RecordType>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/globalValueSets/Customer_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Coinbase Team</fullName>
    </customValue>
    <customValue>
        <fullName>Startup</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Service - Traditional</fullName>
        <isActive>false</isActive>
        <label>Financial Service - Traditional</label>
    </customValue>
    <customValue>
        <fullName>Financial Service - Crypto Native</fullName>
        <isActive>false</isActive>
        <label>Financial Service - Crypto Native</label>
    </customValue>
    <customValue>
        <fullName>Startups</fullName>
        <isActive>false</isActive>
        <label>Startups</label>
    </customValue>
    <masterLabel>Customer Segment</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Customer_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Customer Tier</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other (Unspecified)</fullName>
    </customValue>
    <customValue>
        <fullName>Delegate</fullName>
    </customValue>
    <customValue>
        <fullName>Participate</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange &amp; Pro APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Sign in with Coinbase</fullName>
    </customValue>
    <customValue>
        <fullName>Prime APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Rosetta</fullName>
    </customValue>
    <customValue>
        <fullName>Query &amp; Transact</fullName>
    </customValue>
    <customValue>
        <fullName>Staking</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet-as-a-Service</fullName>
    </customValue>
    <customValue>
        <fullName>NFT</fullName>
    </customValue>
    <customValue>
        <fullName>Data Indexers</fullName>
        <isActive>false</isActive>
        <label>Data Indexers</label>
    </customValue>
    <customValue>
        <fullName>Node</fullName>
        <isActive>false</isActive>
        <label>Node</label>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

src/base/globalValueSets/Protocol_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acala</fullName>
    </customValue>
    <customValue>
        <fullName>Algorand</fullName>
    </customValue>
    <customValue>
        <fullName>Aptos</fullName>
    </customValue>
    <customValue>
        <fullName>Avalanche</fullName>
    </customValue>
    <customValue>
        <fullName>Axelar</fullName>
    </customValue>
    <customValue>
        <fullName>Binance Smart Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin SV</fullName>
    </customValue>
    <customValue>
        <fullName>Cardano</fullName>
    </customValue>
    <customValue>
        <fullName>Celo</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmos</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto.com</fullName>
    </customValue>
    <customValue>
        <fullName>Decred</fullName>
    </customValue>
    <customValue>
        <fullName>Diem</fullName>
    </customValue>
    <customValue>
        <fullName>Dogecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Edgeware</fullName>
    </customValue>
    <customValue>
        <fullName>EOS</fullName>
    </customValue>
    <customValue>
        <fullName>Eth2</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum 1.X</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Evmos</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Helium</fullName>
    </customValue>
    <customValue>
        <fullName>Karura</fullName>
    </customValue>
    <customValue>
        <fullName>Keep</fullName>
    </customValue>
    <customValue>
        <fullName>Kusama</fullName>
    </customValue>
    <customValue>
        <fullName>Litecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Livepeer</fullName>
    </customValue>
    <masterLabel>Protocol List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/classes/TestDataHelper.cls
/**
 * @description       : 
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 11-01-2022
 * @last modified by  : Lavanya Tangati
**/
@isTest
public class TestDataHelper {
    public static Id stdLeadRecTypeId {
        get {
            if (stdLeadRecTypeId == null) {
                stdLeadRecTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Standard_Lead').getRecordTypeId();
            }
            
            return stdLeadRecTypeId;
        }
        private set;
    }
    
    public static Id algoOppRecTypeId {
        get {
            if (algoOppRecTypeId == null) {
                algoOppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Algorand_Pipeline').getRecordTypeId();
            }
            
            return algoOppRecTypeId;
        }
        private set;
    }
    
    public static List<Lead> getStandardLeads(Integer size, Boolean isCreate) {
        List<Lead> leads = new List<Lead>();
        
        for (Integer i = 0; i < size; i++) {
            leads.add(new Lead(
                RecordTypeId = stdLeadRecTypeId,
                FirstName = 'First ' + i,
                LastName = 'Last ' + i,
                Company = 'New York Corp ' + i, 
                Description = 'Test Lead',
                Email = 'test.lead' + i + '@nomail.invalid',
                LeadSource = 'Partner',
                Customer_Segment__c = 'Individual',
                Product_Interest__c = 'Participate'
            ));
        }
        
        if (isCreate) {
            insert leads;
        }
        
        return leads;
    }
    
    public static List<Account> getAccounts(Integer size, Boolean isCreate) {
        List<Account> accounts = new List<Account>();
        
        for (Integer i = 0; i < size; i++) {
            accounts.add(new Account(
                Name = 'Test Account ' + i,
                Size__c = 'Small Cap (< $150M)',
                Ideal_Timezone__c = 'EST - Eastern Standard Time - GMT-5:00',
                Industry = 'Custodian',
                Customer_Tier__c = '1'
            ));
        }
        
        if (isCreate) {
            insert accounts;
        }
        
        return accounts;
    }
    
    public static List<Contact> getContacts(Id accountId, Integer size, Boolean isCreate) {
        List<Contact> contacts = new List<Contact>();
        
        for (Integer i = 0; i < size; i++) {
            contacts.add(new Contact(
                AccountId = accountId,
                FirstName = 'Test ' + i,
                LastName = 'Contact',
                Email = 'test.contact' + i + '@nomail.invalid',
                Phone = '6465551234'
            ));
        }
        
        if (isCreate) {
            insert contacts;
        }
        
        return contacts;
    }
    
    public static List<Opportunity> getOpportunities(Id accountId, Integer size, Boolean isCreate) {
        List<Opportunity> opps = new List<Opportunity>();
        
        for (Integer i = 0; i < size; i++) {
            opps.add(new Opportunity(
                RecordTypeId = algoOppRecTypeId,
                AccountId = accountId,
                Name = 'Test Oppty ' + i,
                CloseDate = System.today().addDays(30),
                StageName = 'Qualification'
            ));
        }
        
        if (isCreate) {
            insert opps;
        }
        
        return opps;
    }
    
    public static void setOpportunityFieldsForWon(List<Opportunity> opps, Id contactId) {
        for (Opportunity opp : opps) {
            opp.StageName = 'Closed Won';
            opp.Product_Interest__c = 'Other (Unspecified)';
            opp.Ideal_Timezone__c = 'EST - Eastern Standard Time - GMT-5:00';
            opp.Primary_Contact__c = contactId;
            opp.Type = 'Upsell';
            opp.Onboarding_Required__c = 'No';
            opp.Other_Amount__c = 10000;
        }
    }

    public static List<Asset>  getAssets(Id accountId, Integer size, Boolean isCreate){
        List<Asset> assets = new List<Asset>();
        
        for (Integer i = 0; i < size; i++) {
            assets.add(new Asset(
                Name = 'Test Asset ' + i,
                Protocol__c = 'Bitcoin',
                Product_Type__c = 'Delegation',
                AccountId = accountId
            ));
        }
        
        if (isCreate) {
            insert assets;
        }
        
        return assets;
    }

    public static Bill__c  getBill(Id accountId, Boolean isCreate){
        Bill__c bill = new Bill__c(
            Name = 'Test Bill' ,
            Billing_Frequency__c = 'Weekly',
            Account__c = accountId
        );
        
        if (isCreate) {
            insert bill;
        }
        
        return bill;
    }

    public static User getUser( String p, Boolean isCreate ) {
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        String uniqueName = UserInfo.getOrganizationId() + dateString + Integer.valueOf(math.rint(math.random()*1000000));
        Profile pr = [select id from profile where name = : p];

        User u = new User( 
                        alias = 'standt', email = uniqueName + '@test' + UserInfo.getOrganizationId() + '.com', 
                        emailencodingkey = 'UTF-8', country = 'US', firstName = 'firstname', lastname = 'lastname', 
                        languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = pr.Id, 
                        timezonesidkey = 'America/Los_Angeles', username = uniqueName + '@test' + UserInfo.getOrganizationId() + '.com'
        );

        if(isCreate) 
            insert u;
            
        return u;
    }

    public static Task getTask(String parentId, Boolean isCreate){
       
        Task t = new Task(
            Subject = 'Call' ,
            Status = 'Open',
            WhatId = parentId,
            Priority='Normal'
        );
        
        if (isCreate) {
            insert t;
        }
        
        return t;
    }
}