src/base/objects/Account/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Date_Override__c.field-meta.xml
<CustomField>
    <fullName>Date_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Date Override</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/Opportunity/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <description>The ideal timezone of this opportunity for onboardings, communication, etc.</description>
    <inlineHelpText>The ideal timezone of this opportunity for onboardings, communication, etc. Required to move a deal to Trial or Closed Won.</inlineHelpText>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Onboarding_Required__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Required__c</fullName>
    <description>OPS-5156</description>
    <inlineHelpText>Please denote whether this customer requires an Onboarding or New Asset Case created. This field is required when the Opportunity is Closed Won.</inlineHelpText>
    <label>Onboarding Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>New Customer - Onboard</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Onboard</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
                <isActive>false</isActive>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Other_Amount__c.field-meta.xml
<CustomField>
    <fullName>Other_Amount__c</fullName>
    <label>Other Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Opportunity/fields/Previously_Closed__c.field-meta.xml
<CustomField>
    <fullName>Previously_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previously Closed</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact associate with this opportunity.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
                <isActive>false</isActive>
                <label>Node</label>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/recordTypes/No_Pipeline.recordType-meta.xml
<RecordType>
    <fullName>No_Pipeline</fullName>
    <active>true</active>
    <businessProcess>Participation Sales Process</businessProcess>
    <description>Does not currently belong to a pipeline</description>
    <label>No Pipeline</label>
</RecordType>

src/base/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other (Unspecified)</fullName>
    </customValue>
    <customValue>
        <fullName>Delegate</fullName>
    </customValue>
    <customValue>
        <fullName>Participate</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange &amp; Pro APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Sign in with Coinbase</fullName>
    </customValue>
    <customValue>
        <fullName>Prime APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Rosetta</fullName>
    </customValue>
    <customValue>
        <fullName>Query &amp; Transact</fullName>
    </customValue>
    <customValue>
        <fullName>Staking</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet-as-a-Service</fullName>
    </customValue>
    <customValue>
        <fullName>NFT</fullName>
    </customValue>
    <customValue>
        <fullName>Data Indexers</fullName>
        <isActive>false</isActive>
        <label>Data Indexers</label>
    </customValue>
    <customValue>
        <fullName>Node</fullName>
        <isActive>false</isActive>
        <label>Node</label>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

src/base/classes/TA_Opportunity_OnboardingCaseHandlerTest.cls
@isTest
private class TA_Opportunity_OnboardingCaseHandlerTest {
   private static final Id WALLET_RT_ID = TA_Opportunity_OnboardingCaseHandler.WALLET_OPPY_RECORDTYPE_ID;
   private static final Id NO_PIPELINE_RT_ID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        												.get('No_Pipeline').getRecordTypeId();
   
    @isTest
    private static void onboardingQueueIdTest() {
      Test.startTest();
        	Id onboardingQueueId = TA_Opportunity_OnboardingCaseHandler.onboardingQueueId;
      Test.stopTest();
        
        System.assertNotEquals(
            NULL,
            onboardingQueueId,
            'DeveloperName "Onboarding_Queue" should returned Id by Salesforce.');
    }
    
    @isTest
    private static void onboardingNotificationIdTest() {
      Test.startTest();
        	Id onboardingNotificationId = TA_Opportunity_OnboardingCaseHandler.onboardingNotificationId;
      Test.stopTest();
        
        System.assertNotEquals(
            NULL,
            onboardingNotificationId,
            'DeveloperName "Onboarding_Notification" should returned Id by Salesforce.');
    }
    
    @isTest
    private static void insert_TrialStageOppy_Test() {
        Opportunity oppyTest = new Opportunity(StageName = 'Trial');
        TA_Opportunity_OnboardingCaseHandler handler = new TA_Opportunity_OnboardingCaseHandler();
        Test.startTest();
        	handler.beforeInsert(new List<Opportunity>{oppyTest});
        	Integer issuedDML = Limits.getDmlStatements();
        	Integer issuedQuery = Limits.getQueries();
        Test.stopTest();
        
        System.assertEquals(
            0,
            issuedDML,
            'When oppy stageName is not "Closed Won", system should skip the record and do not perform any DML operation');
        
        System.assertEquals(
            0,
            issuedQuery,
            'When oppy stageName is not "Closed Won", system should skip the record and do not perform any Query operation');  	
    }
    
    @isTest
    private static void insert_ClosedWon_PreviouslyClosedTrue_Test() {
        Opportunity oppyTest = new Opportunity(StageName = 'Closed Won', Previously_Closed__c = TRUE);
        TA_Opportunity_OnboardingCaseHandler handler = new TA_Opportunity_OnboardingCaseHandler();
        Test.startTest();
        	handler.beforeInsert(new List<Opportunity>{oppyTest});
        	Integer issuedDML = Limits.getDmlStatements();
        	Integer issuedQuery = Limits.getQueries();
        Test.stopTest();
        
        System.assertEquals(
            0,
            issuedDML,
            'When oppy is "Closed Won" but Previously_Closed is True, system should skip the record and do not perform any DML operation');
        
        System.assertEquals(
            0,
            issuedQuery,
            'When oppy is "Closed Won" but Previously_Closed is True, system should skip the record and do not perform any Query operation');  	
    }
    
    @isTest
    private static void insertOnboardingRequiredNo_Test() {
        final String NO_VALUE = TA_Opportunity_OnboardingCaseHandler.NO_VALUE;            
        Opportunity oppyTest = new Opportunity(
            StageName = 'Closed Won', 
            Previously_Closed__c = FALSE, 
            Onboarding_Required__c = NO_VALUE,
        	RecordTypeId = WALLET_RT_ID);
        TA_Opportunity_OnboardingCaseHandler handler = new TA_Opportunity_OnboardingCaseHandler();
        
        Test.startTest();
        	handler.beforeInsert(new List<Opportunity>{oppyTest});
        Test.stopTest();
        
         System.assertEquals(
        	NO_VALUE,
        	oppyTest.Onboarding_Required__c, 
            'When Opportunity is flipped to Closed Won, Previously_Closed is False and Onboarding_Required is "No", '+
             'System should create chatter feed on a record');
    }
    
    @isTest
    private static void insertClosedWithDelegationProductType_Test() {
        final String DELEGATION_VALUE = TA_Opportunity_OnboardingCaseHandler.DELEGATION_PRODUCT_TYPE;
        
         Opportunity oppyTest = new Opportunity(
            StageName = 'Closed Won', 
            Previously_Closed__c = FALSE, 
            Product_Type__c = DELEGATION_VALUE,
        	RecordTypeId = WALLET_RT_ID);
        TA_Opportunity_OnboardingCaseHandler handler = new TA_Opportunity_OnboardingCaseHandler();
            
        Test.startTest();
        	handler.beforeInsert(new List<Opportunity>{oppyTest});
        Test.stopTest();
        
         System.assertEquals(
        	DELEGATION_VALUE,
        	oppyTest.Product_Type__c, 
            'When Opportunity is flipped to Closed Won, Previously_Closed is False and Product Type is "Delegation", '+
             'System should create chatter feed on a record');
    }
    
    @isTest
    private static void updateClosedWonSendNotification_Test() {
       final Date EXPECTED_TODAY_DATE = System.today();
       Account testAccount = TestDataHelper.getAccounts(1, true /*create Account*/)[0];
       Contact testContact = TestDataHelper.getContacts(testAccount.Id, 1, true /*create Contact*/)[0];

        Opportunity testOppy = TestDataHelper.getOpportunities(testAccount.Id, 1, false /*create Oppy*/)[0];
        testOppy.Previously_Closed__c = FALSE;
        testOppy.Product_Interest__c = 'Other (Unspecified)';
		testOppy.Other_Amount__c = 2;
        testOppy.Type = 'Renewal';
        testOppy.Ideal_Timezone__c = 'EST - Eastern Standard Time - GMT-5:00';
        testOppy.Primary_Contact__c = testContact.Id;
		insert testOppy;
        Test.startTest();
       		testOppy.StageName = 'Closed Won';
        	testOppy.Previously_Closed__c = FALSE;
        	testOppy.Date_Override__c = FALSE;
        	testOppy.Onboarding_Required__c = 'New Customer - Onboard';
        	update testOppy;
        Integer issuedCustomNotification = Limits.getMobilePushApexCalls();
        Test.stopTest();
        
        List<Opportunity> queriedOppies = [SELECT Id, CloseDate FROM Opportunity];
        
        System.assertEquals(
            1, 
        	queriedOppies.size(),
        	'Total inserted opportunity should be 1');
        
         System.assertEquals(
            testOppy.Id, 
        	queriedOppies[0].Id,
        	'Queried opportunity should be same as inserted opportunity in the test');
        
        System.assertEquals(
        	EXPECTED_TODAY_DATE,
        	queriedOppies[0].CloseDate, 
            'When Opportunity is flipped to Closed Won and Date Override is False, System should update '+
            'CloseDate to Today');
    }
    
    @isTest
    private static void updateClosedWithDateOverrideFalse_Test() {
        final String DELEGATION_VALUE = TA_Opportunity_OnboardingCaseHandler.DELEGATION_PRODUCT_TYPE;
        Date todayDate = System.today();
         Opportunity oldRecord = new Opportunity(
            Id = fflib_IDGenerator.generate(Opportunity.SobjectType),
            StageName = 'Closed Won', 
            Previously_Closed__c = FALSE,
            CloseDate = todayDate.addDays(-2),
            Date_Override__c = FALSE,
            Product_Type__C = DELEGATION_VALUE,
        	RecordTypeId = NO_PIPELINE_RT_ID);
        
        Opportunity newRecord = oldRecord.clone(true /*clone ids*/, false, false, false);
        newRecord.Product_Type__C = 'Participation';
        
        TA_Opportunity_OnboardingCaseHandler handler = new TA_Opportunity_OnboardingCaseHandler();
            
        Test.startTest();
        	handler.beforeUpdate(new List<Opportunity>{newRecord}, new List<Opportunity>{oldRecord});
        Test.stopTest();
        
         System.assertEquals(
        	todayDate,
        	newRecord.CloseDate, 
            'When Opportunity is flipped to Closed Won and Date Override is False, System should update '+
            'CloseDate to Today');
    }
}