src/base/objects/Account/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The valuation of the company.</description>
    <inlineHelpText>The valuation of the company. This is a fairly loose metric, as a lot of these values are not public information, but use your best judgement.</inlineHelpText>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small Cap (&lt; $150M)</fullName>
                <default>true</default>
                <label>Small Cap (&lt; $150M)</label>
            </value>
            <value>
                <fullName>Mid Cap ($150M &lt; $1B)</fullName>
            </value>
            <value>
                <fullName>Large Cap (&gt; $1B)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The type of product for this asset.</description>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Asset/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>The protocol associated with this asset.</description>
    <label>Protocol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Protocol_List</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <description>The network or protocol</description>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/base/globalValueSets/Protocol_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acala</fullName>
    </customValue>
    <customValue>
        <fullName>Algorand</fullName>
    </customValue>
    <customValue>
        <fullName>Aptos</fullName>
    </customValue>
    <customValue>
        <fullName>Avalanche</fullName>
    </customValue>
    <customValue>
        <fullName>Axelar</fullName>
    </customValue>
    <customValue>
        <fullName>Binance Smart Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Bitcoin SV</fullName>
    </customValue>
    <customValue>
        <fullName>Cardano</fullName>
    </customValue>
    <customValue>
        <fullName>Celo</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmos</fullName>
    </customValue>
    <customValue>
        <fullName>Crypto.com</fullName>
    </customValue>
    <customValue>
        <fullName>Decred</fullName>
    </customValue>
    <customValue>
        <fullName>Diem</fullName>
    </customValue>
    <customValue>
        <fullName>Dogecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Edgeware</fullName>
    </customValue>
    <customValue>
        <fullName>EOS</fullName>
    </customValue>
    <customValue>
        <fullName>Eth2</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum 1.X</fullName>
    </customValue>
    <customValue>
        <fullName>Ethereum Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Evmos</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Helium</fullName>
    </customValue>
    <customValue>
        <fullName>Karura</fullName>
    </customValue>
    <customValue>
        <fullName>Keep</fullName>
    </customValue>
    <customValue>
        <fullName>Kusama</fullName>
    </customValue>
    <customValue>
        <fullName>Litecoin</fullName>
    </customValue>
    <customValue>
        <fullName>Livepeer</fullName>
    </customValue>
    <masterLabel>Protocol List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/base/classes/TestAccountNumberAssets.cls
@isTest
private class TestAccountNumberAssets {
    @isTest static void TestAcctNotNull() {
        Test.startTest();
        Account acct = new Account(Name='Test Account', Size__c='Small Cap (< $150M)', Ideal_Timezone__c='GMT - Greenwich Mean Time - GMT', Industry='Analytics');
        insert acct;
        System.assertNotEquals(null, acct);
        Test.stopTest();
    }
    @isTest static void TestAcctAssetAssoc() {
        Test.startTest();
        Account acct = new Account(Name='Test Account', Size__c='Small Cap (< $150M)', Ideal_Timezone__c='GMT - Greenwich Mean Time - GMT', Industry='Analytics');
        insert acct;
        Asset asset = new Asset(AccountId = acct.Id,
                               Name = 'Asset',
                               Protocol__c = 'Algorand',
                               Product_Type__c = 'Delegation');
        insert asset;
        System.assertEquals(acct.Id, asset.AccountId);
        Test.stopTest();
    }
}