src/base/objects/Account/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Account/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Date_Override__c.field-meta.xml
<CustomField>
    <fullName>Date_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Date Override</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/Opportunity/fields/Ideal_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Timezone__c</fullName>
    <description>The ideal timezone of this opportunity for onboardings, communication, etc.</description>
    <inlineHelpText>The ideal timezone of this opportunity for onboardings, communication, etc. Required to move a deal to Trial or Closed Won.</inlineHelpText>
    <label>Ideal Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezones</valueSetName>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/IsClosedDate_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>IsClosedDate_Current_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFCC-1355: if ClosedDate lies under current year, flow auto update this field to checked. If ClosedDate does not lies in current year by next year 1 Jan, auto schedule flow update this field to unchecked.</description>
    <label>ClosedDate Current Year?</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/Opportunity/fields/Onboarding_Required__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Required__c</fullName>
    <description>OPS-5156</description>
    <inlineHelpText>Please denote whether this customer requires an Onboarding or New Asset Case created. This field is required when the Opportunity is Closed Won.</inlineHelpText>
    <label>Onboarding Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>New Customer - Onboard</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Onboard</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
                <isActive>false</isActive>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Other_Amount__c.field-meta.xml
<CustomField>
    <fullName>Other_Amount__c</fullName>
    <label>Other Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/base/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact associate with this opportunity.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/base/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delegation</fullName>
            </value>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Coinbase Pay SDK</fullName>
            </value>
            <value>
                <fullName>Wallet-as-a-Service</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
                <isActive>false</isActive>
                <label>Node</label>
            </value>
            <value>
                <fullName>QT</fullName>
                <isActive>false</isActive>
                <label>QT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/base/objects/Opportunity/fields/Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mark this box once a post-integration survey has been sent. Required for Closed Won.</inlineHelpText>
    <label>Survey Sent</label>
    <type>Checkbox</type>
</CustomField>

src/base/objects/Opportunity/recordTypes/Cloud_Pipeline.recordType-meta.xml
<RecordType>
    <fullName>Cloud_Pipeline</fullName>
    <active>true</active>
    <businessProcess>Participation Sales Process</businessProcess>
    <label>Cloud Pipeline</label>
</RecordType>

src/base/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other (Unspecified)</fullName>
    </customValue>
    <customValue>
        <fullName>Delegate</fullName>
    </customValue>
    <customValue>
        <fullName>Participate</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Coinbase Pay SDK</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange &amp; Pro APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Sign in with Coinbase</fullName>
    </customValue>
    <customValue>
        <fullName>Prime APIs</fullName>
    </customValue>
    <customValue>
        <fullName>Rosetta</fullName>
    </customValue>
    <customValue>
        <fullName>Query &amp; Transact</fullName>
    </customValue>
    <customValue>
        <fullName>Staking</fullName>
    </customValue>
    <customValue>
        <fullName>Wallet-as-a-Service</fullName>
    </customValue>
    <customValue>
        <fullName>NFT</fullName>
    </customValue>
    <customValue>
        <fullName>Data Indexers</fullName>
        <isActive>false</isActive>
        <label>Data Indexers</label>
    </customValue>
    <customValue>
        <fullName>Node</fullName>
        <isActive>false</isActive>
        <label>Node</label>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

src/base/classes/ResetYtdRevenueBatch_Test.cls
/**
 * @description       : 
 * @author            : Lavanya Tangati
 * @group             : 
 * @last modified on  : 01-05-2023
 * @last modified by  : Lavanya Tangati
**/
@isTest
private without Sharing class ResetYtdRevenueBatch_Test {
    private static final Id CLOUD_PIPELINE_RECORDTYPE_ID = SObjectType.Opportunity
                                                                            .getRecordTypeInfosByDeveloperName()
                                                                            .get('Cloud_Pipeline')
                                                                            .getRecordTypeId();

 	private static final String BATCH_QUERY = 'SELECT Id, IsClosedDate_Current_Year__c FROM Opportunity WHERE IsClosedDate_Current_Year__c = TRUE AND CloseDate = THIS_YEAR'; 
 
   @TestSetup
    static void makeData(){
        GroupMember GM = new GroupMember();
        GM.GroupId = [Select id from Group where Name = 'Onboarding Queue'  AND Type = 'Queue'].Id ;
        GM.UserOrGroupId = UserInfo.getUserId();
        insert GM;
    }

    @isTest
    private static void keyValueMetadata_SuccessTest() {
        final String EXPECTED_FROM_ADDRESS = 'abc@gmail.com';
        ResetYtdRevenueBatch.emailAddresses = new Map<String, String>{'fromAddress'=> EXPECTED_FROM_ADDRESS};
        
        Test.startTest();
        	Map<String, String> actualEmailsMap = ResetYtdRevenueBatch.emailAddresses;
        Test.stopTest();
        
        System.assert(
            actualEmailsMap != NULL, 
            'EmailAddresses map should have typeofEmail with email address value');
        
        System.assertEquals(
            actualEmailsMap.get('fromAddress'),
            EXPECTED_FROM_ADDRESS,
            'actualEmailsMap should have fromAddress key with "abc@gmail.com" value');
         
    }
    @isTest
    private static void batchWithThisYearOpportunity() {
        System.assertEquals([SELECT Id FROM GroUPMember WHERE Group.Name = 'Onboarding Queue' ].size(), 1);

        Account accountRecord = TestDataHelper.getAccounts(1, true)[0];
		Contact contactRecord = createContactRecord(accountRecord, 'ctc-record-test@cointest.com');
        
        Opportunity oppRecord = TestDataHelper.getOpportunities(accountRecord.Id, 1, false)[0];
        oppRecord.RecordTypeId = CLOUD_PIPELINE_RECORDTYPE_ID;
		oppREcord.Type = 'Upsell';
		oppRecord.Primary_Contact__c = contactRecord.Id;
        oppRecord.StageName = 'Closed Won';
        oppRecord.CloseDate = System.today();
        oppRecord.Survey_Sent__c = true;
        oppRecord.Date_Override__c = true;
		oppRecord.Onboarding_Required__c = 'Existing Customer - Onboard';
		oppRecord.Ideal_Timezone__c = 'EST - Eastern Standard Time - GMT-5:00';
		oppRecord.Product_Type__c = 'Coinbase Pay SDK';
		oppRecord.Product_Interest__c = 'Other (Unspecified)';
		oppRecord.Other_Amount__c = 123.45;
        insert oppRecord;

        List<Opportunity> queryOppyRecords = [SELECT Id, IsClosedDate_Current_Year__c FROM Opportunity];
        
        System.assertEquals(
            queryOppyRecords.size(), 
            1, 
            'As system created one opportunity, it should return one opportunity record only');
            
        System.assertEquals(
            queryOppyRecords[0].IsClosedDate_Current_Year__c, 
            TRUE, 
            'Opportunity ClosedDate is THIS_YEAR AND StageName is "Closed Won", IsClosedDate_Current_Year__c should be TRUE by before trigger flow');
            
            
            Test.startTest();
                String query = BATCH_QUERY + ' AND CloseDate = THIS_YEAR';
                Database.executeBatch(new ResetYtdRevenueBatch(query));
            Test.stopTest();
            
        List<Opportunity> queryUpdatedOppyRecords = [SELECT Id, IsClosedDate_Current_Year__c FROM Opportunity];
            
            System.assertEquals(
            queryUpdatedOppyRecords.size(), 
            1, 
            'As system has one opportunity, it should return one opportunity record only');
            
            System.assertEquals(
            queryOppyRecords[0].IsClosedDate_Current_Year__c, 
            TRUE, 
            'Due to flow and opportunity closeWon in THIS_YEAR conditions being met, '+
            'batch run should flip Opportunity.IsClosedDate_Current_Year__c value to false, '+
            'and then update checkbox back to true');
    }

	private static Contact createContactRecord(Account accountRecord, String emailStr){
		Contact contactRecord = new Contact();
		contactRecord.AccountId = accountRecord.Id;
		contactRecord.LastName = 'Ctc-Opp-Test';
		contactRecord.Email = emailStr;
		insert contactRecord;

		return contactRecord;
	}
    
}